"""Analyse Immo — étude de marché communale (version autonome pour hébergement).

Fichier généré par build_site.py : le paquet immo/ est embarqué ci-dessous puis
reconstitué en mémoire au démarrage. Pour modifier le code, éditez les sources du
projet et relancez `python build_site.py`.
"""
import base64 as _b64
import sys as _sys
import types as _types

_SOURCES = {
    "config": (
        "IiIiQ29uZmlndXJhdGlvbiBjb21tdW5lIGRlIGwnYXBwbGljYXRpb24uIiIiCmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3Rh"
        "dGlvbnMKCmltcG9ydCBvcwpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCkFQUF9OQU1FID0gIkFuYWx5c2UgSW1tbyIKVVNFUl9B"
        "R0VOVCA9ICJhbmFseXNlLWltbW8vMS4wIChvdXRpbCBwZXJzb25uZWwgZCdldHVkZSBkZSBtYXJjaGUpIgpIVFRQX1RJTUVPVVQg"
        "PSA2MAoKQ0FDSEVfRElSID0gUGF0aChvcy5lbnZpcm9uLmdldCgiQU5BTFlTRV9JTU1PX0NBQ0hFIiwgUGF0aC5ob21lKCkgLyAi"
        "LmFuYWx5c2UtaW1tbyIpKQpEVkZfQ0FDSEUgPSBDQUNIRV9ESVIgLyAiZHZmIgpQT1BfQ0FDSEUgPSBDQUNIRV9ESVIgLyAicG9w"
        "dWxhdGlvbiIKCmZvciBfZCBpbiAoQ0FDSEVfRElSLCBEVkZfQ0FDSEUsIFBPUF9DQUNIRSk6CiAgICBfZC5ta2RpcihwYXJlbnRz"
        "PVRydWUsIGV4aXN0X29rPVRydWUpCgojIFNvdXJjZXMKR0VPX0FQSSA9ICJodHRwczovL2dlby5hcGkuZ291di5mciIKRFZGX0JB"
        "U0UgPSAiaHR0cHM6Ly9maWxlcy5kYXRhLmdvdXYuZnIvZ2VvLWR2Zi9sYXRlc3QvY3N2IgpORVdTX1JTUyA9ICJodHRwczovL25l"
        "d3MuZ29vZ2xlLmNvbS9yc3Mvc2VhcmNoIgoKIyBNaWxsZXNpbWVzIGRlIHBvcHVsYXRpb25zIGxlZ2FsZXMgcHVibGllcyBwYXIg"
        "bCdJbnNlZSAocGFnZSAtPiBpZGVudGlmaWFudCBkZSBmaWNoaWVyKS4KIyBBam91dGVyIHVuZSBsaWduZSBxdWFuZCBsJ0luc2Vl"
        "IHB1YmxpZSB1biBub3V2ZWF1IG1pbGxlc2ltZS4KSU5TRUVfUE9QX0ZJTEVTID0gewogICAgMjAyMzogIjg2ODA3MjYiLAogICAg"
        "MjAyMTogIjc3Mzk1ODIiLAogICAgMjAyMDogIjY2ODMwMzUiLAogICAgMjAxOTogIjYwMTEwNzAiLAogICAgMjAxODogIjQ5ODk3"
        "MjQiLAp9CgojIEJvcm5lcyBkZSBuZXR0b3lhZ2UgZGVzIHByaXggYXUgbTIgKGV1cm9zKSwgcG91ciBlY2FydGVyIGxlcyB2YWxl"
        "dXJzIGFiZXJyYW50ZXMuClBSSVhfTTJfTUlOID0gMjAwClBSSVhfTTJfTUFYID0gMzAwMDAKU1VSRkFDRV9NSU4gPSA5ClNVUkZB"
        "Q0VfTUFYID0gMTAwMApWQUxFVVJfTUlOID0gNTAwMAo="
    ),
    "http": (
        "IiIiQWNjZXMgcmVzZWF1IG11dHVhbGlzZSAoc2Vzc2lvbiByZXF1ZXN0cyArIGdlc3Rpb24gZCdlcnJldXJzIGxpc2libGUpLiIi"
        "Igpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFubm90YXRpb25zCgppbXBvcnQgcmVxdWVzdHMKCmZyb20gLmNvbmZpZyBpbXBvcnQg"
        "SFRUUF9USU1FT1VULCBVU0VSX0FHRU5UCgpfc2Vzc2lvbiA9IE5vbmUKCgpkZWYgc2Vzc2lvbigpIC0+IHJlcXVlc3RzLlNlc3Np"
        "b246CiAgICBnbG9iYWwgX3Nlc3Npb24KICAgIGlmIF9zZXNzaW9uIGlzIE5vbmU6CiAgICAgICAgcyA9IHJlcXVlc3RzLlNlc3Np"
        "b24oKQogICAgICAgIHMuaGVhZGVycy51cGRhdGUoeyJVc2VyLUFnZW50IjogVVNFUl9BR0VOVH0pCiAgICAgICAgX3Nlc3Npb24g"
        "PSBzCiAgICByZXR1cm4gX3Nlc3Npb24KCgpjbGFzcyBTb3VyY2VFcnJvcihSdW50aW1lRXJyb3IpOgogICAgIiIiRXJyZXVyIGRl"
        "IHJlY3VwZXJhdGlvbiBkJ3VuZSBzb3VyY2UgZGUgZG9ubmVlcy4iIiIKCgpkZWYgZ2V0KHVybDogc3RyLCBwYXJhbXM6IGRpY3Qg"
        "fCBOb25lID0gTm9uZSwgdGltZW91dDogaW50ID0gSFRUUF9USU1FT1VULCBzdHJlYW06IGJvb2wgPSBGYWxzZSk6CiAgICB0cnk6"
        "CiAgICAgICAgciA9IHNlc3Npb24oKS5nZXQodXJsLCBwYXJhbXM9cGFyYW1zLCB0aW1lb3V0PXRpbWVvdXQsIHN0cmVhbT1zdHJl"
        "YW0pCiAgICBleGNlcHQgcmVxdWVzdHMuUmVxdWVzdEV4Y2VwdGlvbiBhcyBleGM6ICAjIHJlc2VhdSBjb3VwZSwgRE5TLCBwcm94"
        "eS4uLgogICAgICAgIHJhaXNlIFNvdXJjZUVycm9yKGYiQWNjZXMgaW1wb3NzaWJsZSBhIHt1cmx9ICh7ZXhjLl9fY2xhc3NfXy5f"
        "X25hbWVfX30pIikgZnJvbSBleGMKICAgIHJldHVybiByCgoKZGVmIGdldF9qc29uKHVybDogc3RyLCBwYXJhbXM6IGRpY3QgfCBO"
        "b25lID0gTm9uZSk6CiAgICByID0gZ2V0KHVybCwgcGFyYW1zPXBhcmFtcykKICAgIGlmIHIuc3RhdHVzX2NvZGUgIT0gMjAwOgog"
        "ICAgICAgIHJhaXNlIFNvdXJjZUVycm9yKGYiUmVwb25zZSB7ci5zdGF0dXNfY29kZX0gZGUge3VybH0iKQogICAgdHJ5OgogICAg"
        "ICAgIHJldHVybiByLmpzb24oKQogICAgZXhjZXB0IFZhbHVlRXJyb3IgYXMgZXhjOgogICAgICAgIHJhaXNlIFNvdXJjZUVycm9y"
        "KGYiUmVwb25zZSBpbGxpc2libGUgZGUge3VybH0iKSBmcm9tIGV4Ywo="
    ),
    "geo": (
        "IiIiUmVjaGVyY2hlIGRlIGNvbW11bmVzIHZpYSBsJ0FQSSBEZWNvdXBhZ2UgYWRtaW5pc3RyYXRpZiAoZ2VvLmFwaS5nb3V2LmZy"
        "KS4iIiIKZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKZnJvbSBmdW5jdG9vbHMgaW1wb3J0IGxydV9jYWNoZQoK"
        "ZnJvbSAuY29uZmlnIGltcG9ydCBHRU9fQVBJCmZyb20gLmh0dHAgaW1wb3J0IFNvdXJjZUVycm9yLCBnZXRfanNvbgoKRklFTERT"
        "ID0gIm5vbSxjb2RlLGNvZGVEZXBhcnRlbWVudCxjb2RlUmVnaW9uLGNvZGVzUG9zdGF1eCxwb3B1bGF0aW9uLGNlbnRyZSxzaXJl"
        "bixjb2RlRXBjaSIKCgpAbHJ1X2NhY2hlKG1heHNpemU9MjU2KQpkZWYgcmVjaGVyY2hlcihub206IHN0ciwgbGltaXRlOiBpbnQg"
        "PSAxMikgLT4gdHVwbGVbZGljdCwgLi4uXToKICAgICIiIkNvbW11bmVzIGRvbnQgbGUgbm9tIGNvcnJlc3BvbmQgYSBsYSBzYWlz"
        "aWUsIGxlcyBwbHVzIHBldXBsZWVzIGQnYWJvcmQuIiIiCiAgICBub20gPSAobm9tIG9yICIiKS5zdHJpcCgpCiAgICBpZiBsZW4o"
        "bm9tKSA8IDI6CiAgICAgICAgcmV0dXJuICgpCiAgICBwYXJhbXMgPSB7Im5vbSI6IG5vbSwgImZpZWxkcyI6IEZJRUxEUywgImJv"
        "b3N0IjogInBvcHVsYXRpb24iLCAibGltaXQiOiBsaW1pdGV9CiAgICBkYXRhID0gZ2V0X2pzb24oZiJ7R0VPX0FQSX0vY29tbXVu"
        "ZXMiLCBwYXJhbXM9cGFyYW1zKQogICAgcmV0dXJuIHR1cGxlKGRhdGEpCgoKQGxydV9jYWNoZShtYXhzaXplPTI1NikKZGVmIHBh"
        "cl9jb2RlX3Bvc3RhbChjcDogc3RyKSAtPiB0dXBsZVtkaWN0LCAuLi5dOgogICAgZGF0YSA9IGdldF9qc29uKGYie0dFT19BUEl9"
        "L2NvbW11bmVzIiwgcGFyYW1zPXsiY29kZVBvc3RhbCI6IGNwLCAiZmllbGRzIjogRklFTERTfSkKICAgIHJldHVybiB0dXBsZShk"
        "YXRhKQoKCkBscnVfY2FjaGUobWF4c2l6ZT01MTIpCmRlZiBwYXJfY29kZShjb2RlX2luc2VlOiBzdHIpIC0+IGRpY3Q6CiAgICBy"
        "ZXR1cm4gZ2V0X2pzb24oZiJ7R0VPX0FQSX0vY29tbXVuZXMve2NvZGVfaW5zZWV9IiwgcGFyYW1zPXsiZmllbGRzIjogRklFTERT"
        "fSkKCgpAbHJ1X2NhY2hlKG1heHNpemU9MjU2KQpkZWYgY29tbXVuZXNfZHVfZGVwYXJ0ZW1lbnQoY29kZV9kZXA6IHN0cikgLT4g"
        "dHVwbGVbZGljdCwgLi4uXToKICAgIGRhdGEgPSBnZXRfanNvbihmIntHRU9fQVBJfS9kZXBhcnRlbWVudHMve2NvZGVfZGVwfS9j"
        "b21tdW5lcyIsIHBhcmFtcz17ImZpZWxkcyI6IEZJRUxEU30pCiAgICByZXR1cm4gdHVwbGUoZGF0YSkKCgpkZWYgY2hlcmNoZXIo"
        "c2Fpc2llOiBzdHIsIGxpbWl0ZTogaW50ID0gMTIpIC0+IGxpc3RbZGljdF06CiAgICAiIiJSZWNoZXJjaGUgdG9sZXJhbnRlIDog"
        "bm9tIGRlIGNvbW11bmUgb3UgY29kZSBwb3N0YWwuIiIiCiAgICBzYWlzaWUgPSAoc2Fpc2llIG9yICIiKS5zdHJpcCgpCiAgICBp"
        "ZiBub3Qgc2Fpc2llOgogICAgICAgIHJldHVybiBbXQogICAgdHJ5OgogICAgICAgIGlmIHNhaXNpZS5pc2RpZ2l0KCkgYW5kIGxl"
        "bihzYWlzaWUpID09IDU6CiAgICAgICAgICAgIHJlc3VsdGF0cyA9IGxpc3QocGFyX2NvZGVfcG9zdGFsKHNhaXNpZSkpCiAgICAg"
        "ICAgICAgIGlmIG5vdCByZXN1bHRhdHM6ICAjIHBldXQtZXRyZSB1biBjb2RlIEluc2VlCiAgICAgICAgICAgICAgICB0cnk6CiAg"
        "ICAgICAgICAgICAgICAgICAgcmVzdWx0YXRzID0gW3Bhcl9jb2RlKHNhaXNpZSldCiAgICAgICAgICAgICAgICBleGNlcHQgU291"
        "cmNlRXJyb3I6CiAgICAgICAgICAgICAgICAgICAgcmVzdWx0YXRzID0gW10KICAgICAgICBlbHNlOgogICAgICAgICAgICByZXN1"
        "bHRhdHMgPSBsaXN0KHJlY2hlcmNoZXIoc2Fpc2llLCBsaW1pdGUpKQogICAgZXhjZXB0IFNvdXJjZUVycm9yOgogICAgICAgIHJh"
        "aXNlCiAgICByZXN1bHRhdHMuc29ydChrZXk9bGFtYmRhIGM6IGMuZ2V0KCJwb3B1bGF0aW9uIikgb3IgMCwgcmV2ZXJzZT1UcnVl"
        "KQogICAgcmV0dXJuIHJlc3VsdGF0c1s6bGltaXRlXQoKCmRlZiBsaWJlbGxlKGNvbW11bmU6IGRpY3QpIC0+IHN0cjoKICAgIGNw"
        "ID0gKGNvbW11bmUuZ2V0KCJjb2Rlc1Bvc3RhdXgiKSBvciBbIiJdKVswXQogICAgcG9wID0gY29tbXVuZS5nZXQoInBvcHVsYXRp"
        "b24iKQogICAgcG9wX3R4dCA9IGYiIOKAlCB7cG9wOix9IGhhYi4iLnJlcGxhY2UoIiwiLCAiICIpIGlmIHBvcCBlbHNlICIiCiAg"
        "ICByZXR1cm4gZiJ7Y29tbXVuZS5nZXQoJ25vbScpfSAoe2NwfSwge2NvbW11bmUuZ2V0KCdjb2RlRGVwYXJ0ZW1lbnQnKX0pe3Bv"
        "cF90eHR9Igo="
    ),
    "population": (
        "IiIiUG9wdWxhdGlvbnMgbGVnYWxlcyBJbnNlZSA6IHJlY3VwZXJhdGlvbiwgbWlzZSBlbiBjYWNoZSBldCBldm9sdXRpb25zLgoK"
        "U291cmNlIDogZmljaGllcnMgZCdlbnNlbWJsZSBkZXMgcG9wdWxhdGlvbnMgbGVnYWxlcyBwdWJsaWVzIHBhciBsJ0luc2VlCiho"
        "dHRwczovL3d3dy5pbnNlZS5mci9mci9zdGF0aXN0aXF1ZXMvZmljaGllci88aWQ+L2Vuc2VtYmxlLnppcCkuCkNoYXF1ZSBtaWxs"
        "ZXNpbWUgZG9ubmUgbGEgcG9wdWxhdGlvbiBtdW5pY2lwYWxlIGRlIHRvdXRlcyBsZXMgY29tbXVuZXMgcG91cgpsJ2FubmVlIGNv"
        "bnNpZGVyZWUuIExlIHBhcnNpbmcgZXN0IHZvbG9udGFpcmVtZW50IHRvbGVyYW50IDogbCdJbnNlZSBmYWl0CmV2b2x1ZXIgbCdp"
        "bnRpdHVsZSBkZXMgY29sb25uZXMgZXQgbGEgcG9zaXRpb24gZGUgbGEgbGlnbmUgZCdlbi10ZXRlLgoiIiIKZnJvbSBfX2Z1dHVy"
        "ZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGlvCmltcG9ydCBqc29uCmltcG9ydCByZQppbXBvcnQgemlwZmlsZQoKaW1w"
        "b3J0IHBhbmRhcyBhcyBwZAoKZnJvbSAuY29uZmlnIGltcG9ydCBJTlNFRV9QT1BfRklMRVMsIFBPUF9DQUNIRQpmcm9tIC5odHRw"
        "IGltcG9ydCBTb3VyY2VFcnJvciwgZ2V0CgpVUkxfTU9ERUxFID0gImh0dHBzOi8vd3d3Lmluc2VlLmZyL2ZyL3N0YXRpc3RpcXVl"
        "cy9maWNoaWVyL3tpZGVudH0vZW5zZW1ibGUuemlwIgoKX0NPTF9ERVAgPSByZS5jb21waWxlKHIiXihjb2QpP2RlcCIsIHJlLkkp"
        "Cl9DT0xfQ09NID0gcmUuY29tcGlsZShyIl4oY29kKT9jb20kfF5jb2RnZW8kfF5kZXBjb20kfF5jb2RlY29tbXVuZSQiLCByZS5J"
        "KQpfQ09MX1BNVU4gPSByZS5jb21waWxlKHIicG11bnxwb3B1bGF0aW9uXHMqbXVuaWNpcGFsZSIsIHJlLkkpCl9DT0xfUFRPVCA9"
        "IHJlLmNvbXBpbGUociJwdG90fHBvcHVsYXRpb25ccyp0b3RhbGUiLCByZS5JKQoKCmRlZiBfbGlyZV9jc3ZfdG9sZXJhbnQoY29u"
        "dGVudTogYnl0ZXMpIC0+IHBkLkRhdGFGcmFtZToKICAgICIiIkxpdCB1biBDU1YgSW5zZWUgc2FucyBjb25uYWl0cmUgYSBsJ2F2"
        "YW5jZSBzZXBhcmF0ZXVyLCBlbmNvZGFnZSBuaSBlbi10ZXRlLiIiIgogICAgZGVybmllciA9IE5vbmUKICAgIGZvciBlbmNvZGFn"
        "ZSBpbiAoInV0Zi04LXNpZyIsICJ1dGYtOCIsICJsYXRpbi0xIik6CiAgICAgICAgdHJ5OgogICAgICAgICAgICB0ZXh0ZSA9IGNv"
        "bnRlbnUuZGVjb2RlKGVuY29kYWdlKQogICAgICAgIGV4Y2VwdCBVbmljb2RlRGVjb2RlRXJyb3I6CiAgICAgICAgICAgIGNvbnRp"
        "bnVlCiAgICAgICAgbGlnbmVzID0gdGV4dGUuc3BsaXRsaW5lcygpCiAgICAgICAgc2VwYXJhdGV1ciA9ICI7IiBpZiB0ZXh0ZS5j"
        "b3VudCgiOyIpID49IHRleHRlLmNvdW50KCIsIikgZWxzZSAiLCIKICAgICAgICAjIEwnZW4tdGV0ZSBlc3QgbGEgcHJlbWllcmUg"
        "bGlnbmUgY29udGVuYW50IHVuZSBjb2xvbm5lIGRlIHBvcHVsYXRpb24uCiAgICAgICAgbGlnbmVfZW50ZXRlID0gMAogICAgICAg"
        "IGZvciBpLCBsaWduZSBpbiBlbnVtZXJhdGUobGlnbmVzWzoxNV0pOgogICAgICAgICAgICBpZiBfQ09MX1BNVU4uc2VhcmNoKGxp"
        "Z25lKSBvciBfQ09MX1BUT1Quc2VhcmNoKGxpZ25lKToKICAgICAgICAgICAgICAgIGxpZ25lX2VudGV0ZSA9IGkKICAgICAgICAg"
        "ICAgICAgIGJyZWFrCiAgICAgICAgdHJ5OgogICAgICAgICAgICByZXR1cm4gcGQucmVhZF9jc3YoCiAgICAgICAgICAgICAgICBp"
        "by5TdHJpbmdJTygiXG4iLmpvaW4obGlnbmVzW2xpZ25lX2VudGV0ZTpdKSksCiAgICAgICAgICAgICAgICBzZXA9c2VwYXJhdGV1"
        "ciwKICAgICAgICAgICAgICAgIGR0eXBlPXN0ciwKICAgICAgICAgICAgICAgIGVuZ2luZT0icHl0aG9uIiwKICAgICAgICAgICAg"
        "KQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOiAgIyBub3FhOiBCTEUwMDEgLSBvbiBlc3NhaWUgbCdlbmNvZGFnZSBz"
        "dWl2YW50CiAgICAgICAgICAgIGRlcm5pZXIgPSBleGMKICAgIHJhaXNlIFNvdXJjZUVycm9yKGYiRmljaGllciBJbnNlZSBpbGxp"
        "c2libGUgKHtkZXJuaWVyfSkiKQoKCmRlZiBfbm9ybWFsaXNlcihkZjogcGQuRGF0YUZyYW1lKSAtPiBwZC5EYXRhRnJhbWU6CiAg"
        "ICBjb2xvbm5lcyA9IHtjOiBjLnN0cmlwKCkgZm9yIGMgaW4gZGYuY29sdW1uc30KICAgIGRmID0gZGYucmVuYW1lKGNvbHVtbnM9"
        "Y29sb25uZXMpCiAgICBjb2xfZGVwID0gbmV4dCgoYyBmb3IgYyBpbiBkZi5jb2x1bW5zIGlmIF9DT0xfREVQLnNlYXJjaChjKSks"
        "IE5vbmUpCiAgICBjb2xfY29tID0gbmV4dCgoYyBmb3IgYyBpbiBkZi5jb2x1bW5zIGlmIF9DT0xfQ09NLnNlYXJjaChjKSksIE5v"
        "bmUpCiAgICBjb2xfcG9wID0gbmV4dCgoYyBmb3IgYyBpbiBkZi5jb2x1bW5zIGlmIF9DT0xfUE1VTi5zZWFyY2goYykpLCBOb25l"
        "KQogICAgaWYgY29sX3BvcCBpcyBOb25lOgogICAgICAgIGNvbF9wb3AgPSBuZXh0KChjIGZvciBjIGluIGRmLmNvbHVtbnMgaWYg"
        "X0NPTF9QVE9ULnNlYXJjaChjKSksIE5vbmUpCiAgICBpZiBjb2xfY29tIGlzIE5vbmUgb3IgY29sX3BvcCBpcyBOb25lOgogICAg"
        "ICAgIHJhaXNlIFNvdXJjZUVycm9yKAogICAgICAgICAgICAiQ29sb25uZXMgSW5zZWUgaW50cm91dmFibGVzIChhdHRlbmR1IHVu"
        "IGNvZGUgY29tbXVuZSBldCB1bmUgcG9wdWxhdGlvbiBtdW5pY2lwYWxlKSA7ICIKICAgICAgICAgICAgZiJjb2xvbm5lcyBsdWVz"
        "IDoge2xpc3QoZGYuY29sdW1ucylbOjEyXX0iCiAgICAgICAgKQoKICAgIGNvZGVfY29tID0gZGZbY29sX2NvbV0uYXN0eXBlKHN0"
        "cikuc3RyLnN0cmlwKCkKICAgIGlmIGNvbF9kZXAgaXMgbm90IE5vbmUgYW5kIGNvZGVfY29tLnN0ci5sZW4oKS5tYXgoKSA8PSAz"
        "OgogICAgICAgIGNvZGVfZGVwID0gZGZbY29sX2RlcF0uYXN0eXBlKHN0cikuc3RyLnN0cmlwKCkuc3RyLnpmaWxsKDIpCiAgICAg"
        "ICAgY29kZSA9IGNvZGVfZGVwICsgY29kZV9jb20uc3RyLnpmaWxsKDMpCiAgICBlbHNlOgogICAgICAgIGNvZGUgPSBjb2RlX2Nv"
        "bS5zdHIuemZpbGwoNSkKCiAgICBwb3AgPSAoCiAgICAgICAgZGZbY29sX3BvcF0KICAgICAgICAuYXN0eXBlKHN0cikKICAgICAg"
        "ICAuc3RyLnJlcGxhY2UociJbXHPCoF0iLCAiIiwgcmVnZXg9VHJ1ZSkKICAgICAgICAuc3RyLnJlcGxhY2UoIiwiLCAiLiIsIHJl"
        "Z2V4PUZhbHNlKQogICAgKQogICAgb3V0ID0gcGQuRGF0YUZyYW1lKHsiY29kZSI6IGNvZGUsICJwb3B1bGF0aW9uIjogcGQudG9f"
        "bnVtZXJpYyhwb3AsIGVycm9ycz0iY29lcmNlIil9KQogICAgb3V0ID0gb3V0LmRyb3BuYShzdWJzZXQ9WyJwb3B1bGF0aW9uIl0p"
        "CiAgICBvdXQgPSBvdXRbb3V0WyJjb2RlIl0uc3RyLmZ1bGxtYXRjaChyIigyW0FCXVswLTldezN9fFswLTldezV9KSIpXQogICAg"
        "cmV0dXJuIG91dC5kcm9wX2R1cGxpY2F0ZXMoc3Vic2V0PSJjb2RlIikuc2V0X2luZGV4KCJjb2RlIilbInBvcHVsYXRpb24iXS5h"
        "c3R5cGUoaW50KS50b19mcmFtZSgpCgoKZGVmIF9jaGFyZ2VyX21pbGxlc2ltZShhbm5lZTogaW50KSAtPiBwZC5EYXRhRnJhbWU6"
        "CiAgICAiIiJQb3B1bGF0aW9uIG11bmljaXBhbGUgZGUgdG91dGVzIGxlcyBjb21tdW5lcyBwb3VyIHVuIG1pbGxlc2ltZSwgYXZl"
        "YyBjYWNoZSBkaXNxdWUuIiIiCiAgICBjYWNoZSA9IFBPUF9DQUNIRSAvIGYicG9wX3thbm5lZX0uY3N2IgogICAgaWYgY2FjaGUu"
        "ZXhpc3RzKCk6CiAgICAgICAgcmV0dXJuIHBkLnJlYWRfY3N2KGNhY2hlLCBkdHlwZT17ImNvZGUiOiBzdHJ9KS5zZXRfaW5kZXgo"
        "ImNvZGUiKQoKICAgIGlkZW50ID0gSU5TRUVfUE9QX0ZJTEVTW2FubmVlXQogICAgcmVwb25zZSA9IGdldChVUkxfTU9ERUxFLmZv"
        "cm1hdChpZGVudD1pZGVudCkpCiAgICBpZiByZXBvbnNlLnN0YXR1c19jb2RlICE9IDIwMDoKICAgICAgICByYWlzZSBTb3VyY2VF"
        "cnJvcihmIkluc2VlIHthbm5lZX0gOiByZXBvbnNlIHtyZXBvbnNlLnN0YXR1c19jb2RlfSIpCgogICAgY29udGVudSA9IHJlcG9u"
        "c2UuY29udGVudAogICAgaWYgY29udGVudVs6Ml0gPT0gYiJQSyI6CiAgICAgICAgd2l0aCB6aXBmaWxlLlppcEZpbGUoaW8uQnl0"
        "ZXNJTyhjb250ZW51KSkgYXMgejoKICAgICAgICAgICAgbm9tcyA9IFtuIGZvciBuIGluIHoubmFtZWxpc3QoKSBpZiBuLmxvd2Vy"
        "KCkuZW5kc3dpdGgoIi5jc3YiKV0KICAgICAgICAgICAgaWYgbm90IG5vbXM6CiAgICAgICAgICAgICAgICByYWlzZSBTb3VyY2VF"
        "cnJvcihmIkluc2VlIHthbm5lZX0gOiBhdWN1biBDU1YgZGFucyBsJ2FyY2hpdmUiKQogICAgICAgICAgICAjIExlIGZpY2hpZXIg"
        "Y29tbXVuYWwgZXN0IGxlIHBsdXMgdm9sdW1pbmV1eCBkZSBsJ2FyY2hpdmUuCiAgICAgICAgICAgIG5vbSA9IG1heChub21zLCBr"
        "ZXk9bGFtYmRhIG46IHouZ2V0aW5mbyhuKS5maWxlX3NpemUpCiAgICAgICAgICAgIGJydXQgPSB6LnJlYWQobm9tKQogICAgZWxz"
        "ZToKICAgICAgICBicnV0ID0gY29udGVudQoKICAgIGRmID0gX25vcm1hbGlzZXIoX2xpcmVfY3N2X3RvbGVyYW50KGJydXQpKQog"
        "ICAgZGYudG9fY3N2KGNhY2hlKQogICAgcmV0dXJuIGRmCgoKZGVmIHNlcmllX2NvbW11bmUoY29kZV9pbnNlZTogc3RyKSAtPiBk"
        "aWN0W2ludCwgaW50XToKICAgICIiIlBvcHVsYXRpb24gbXVuaWNpcGFsZSBkZSBsYSBjb21tdW5lIHBvdXIgY2hhcXVlIG1pbGxl"
        "c2ltZSBkaXNwb25pYmxlLiIiIgogICAgc2VyaWU6IGRpY3RbaW50LCBpbnRdID0ge30KICAgIGVycmV1cnM6IGxpc3Rbc3RyXSA9"
        "IFtdCiAgICBmb3IgYW5uZWUgaW4gc29ydGVkKElOU0VFX1BPUF9GSUxFUywgcmV2ZXJzZT1UcnVlKToKICAgICAgICB0cnk6CiAg"
        "ICAgICAgICAgIHRhYmxlID0gX2NoYXJnZXJfbWlsbGVzaW1lKGFubmVlKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhj"
        "OiAgIyBub3FhOiBCTEUwMDEgLSB1biBtaWxsZXNpbWUgYWJzZW50IG5lIGJsb3F1ZSBwYXMgbGUgcmVzdGUKICAgICAgICAgICAg"
        "ZXJyZXVycy5hcHBlbmQoZiJ7YW5uZWV9OiB7ZXhjfSIpCiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgaWYgY29kZV9pbnNl"
        "ZSBpbiB0YWJsZS5pbmRleDoKICAgICAgICAgICAgc2VyaWVbYW5uZWVdID0gaW50KHRhYmxlLmxvY1tjb2RlX2luc2VlLCAicG9w"
        "dWxhdGlvbiJdKQogICAgaWYgbm90IHNlcmllIGFuZCBlcnJldXJzOgogICAgICAgIHJhaXNlIFNvdXJjZUVycm9yKCJQb3B1bGF0"
        "aW9ucyBJbnNlZSBpbmRpc3BvbmlibGVzIOKAlCAiICsgIiB8ICIuam9pbihlcnJldXJzKSkKICAgIHJldHVybiBkaWN0KHNvcnRl"
        "ZChzZXJpZS5pdGVtcygpKSkKCgpkZWYgX3ZhcmlhdGlvbihzZXJpZTogZGljdFtpbnQsIGludF0sIHJlY3VsOiBpbnQpIC0+IGRp"
        "Y3QgfCBOb25lOgogICAgaWYgbm90IHNlcmllOgogICAgICAgIHJldHVybiBOb25lCiAgICBhbm5lZXMgPSBzb3J0ZWQoc2VyaWUp"
        "CiAgICBmaW4gPSBhbm5lZXNbLTFdCiAgICBjaWJsZSA9IGZpbiAtIHJlY3VsCiAgICBjYW5kaWRhdGVzID0gW2EgZm9yIGEgaW4g"
        "YW5uZWVzIGlmIGEgPD0gY2libGVdCiAgICBpZiBub3QgY2FuZGlkYXRlczoKICAgICAgICByZXR1cm4gTm9uZQogICAgZGVidXQg"
        "PSBjYW5kaWRhdGVzWy0xXQogICAgaWYgZGVidXQgPT0gZmluOgogICAgICAgIHJldHVybiBOb25lCiAgICBlY2FydCA9IHNlcmll"
        "W2Zpbl0gLSBzZXJpZVtkZWJ1dF0KICAgIHBjdCA9IGVjYXJ0IC8gc2VyaWVbZGVidXRdICogMTAwIGlmIHNlcmllW2RlYnV0XSBl"
        "bHNlIE5vbmUKICAgIGR1cmVlID0gZmluIC0gZGVidXQKICAgIHRjYW0gPSAoKHNlcmllW2Zpbl0gLyBzZXJpZVtkZWJ1dF0pICoq"
        "ICgxIC8gZHVyZWUpIC0gMSkgKiAxMDAgaWYgc2VyaWVbZGVidXRdIGFuZCBkdXJlZSBlbHNlIE5vbmUKICAgIHJldHVybiB7CiAg"
        "ICAgICAgImFubmVlX2RlYnV0IjogZGVidXQsCiAgICAgICAgImFubmVlX2ZpbiI6IGZpbiwKICAgICAgICAicG9wdWxhdGlvbl9k"
        "ZWJ1dCI6IHNlcmllW2RlYnV0XSwKICAgICAgICAicG9wdWxhdGlvbl9maW4iOiBzZXJpZVtmaW5dLAogICAgICAgICJ2YXJpYXRp"
        "b24iOiBlY2FydCwKICAgICAgICAidmFyaWF0aW9uX3BjdCI6IHBjdCwKICAgICAgICAidGNhbV9wY3QiOiB0Y2FtLAogICAgICAg"
        "ICJkdXJlZSI6IGR1cmVlLAogICAgfQoKCmRlZiBhbmFseXNlKGNvZGVfaW5zZWU6IHN0ciwgcG9wdWxhdGlvbl9zZWNvdXJzOiBp"
        "bnQgfCBOb25lID0gTm9uZSkgLT4gZGljdDoKICAgICIiIlNlcmllIGRlIHBvcHVsYXRpb24gZXQgdmFyaWF0aW9ucyBhIDIgYW5z"
        "IGV0IDUgYW5zLiIiIgogICAgdHJ5OgogICAgICAgIHNlcmllID0gc2VyaWVfY29tbXVuZShjb2RlX2luc2VlKQogICAgICAgIG1l"
        "c3NhZ2UgPSBOb25lCiAgICBleGNlcHQgU291cmNlRXJyb3IgYXMgZXhjOgogICAgICAgIHNlcmllLCBtZXNzYWdlID0ge30sIHN0"
        "cihleGMpCgogICAgcmVzdWx0YXQgPSB7CiAgICAgICAgInNlcmllIjogc2VyaWUsCiAgICAgICAgImNvdXJ0X3Rlcm1lIjogX3Zh"
        "cmlhdGlvbihzZXJpZSwgMiksCiAgICAgICAgIm1veWVuX3Rlcm1lIjogX3ZhcmlhdGlvbihzZXJpZSwgNSksCiAgICAgICAgIm1l"
        "c3NhZ2UiOiBtZXNzYWdlLAogICAgICAgICJzb3VyY2UiOiAiSW5zZWUg4oCUIHBvcHVsYXRpb25zIGxlZ2FsZXMgKHJlY2Vuc2Vt"
        "ZW50KSIsCiAgICB9CiAgICBpZiBub3Qgc2VyaWUgYW5kIHBvcHVsYXRpb25fc2Vjb3VyczoKICAgICAgICByZXN1bHRhdFsic2Vy"
        "aWUiXSA9IHt9CiAgICAgICAgcmVzdWx0YXRbInBvcHVsYXRpb25fYWN0dWVsbGUiXSA9IHBvcHVsYXRpb25fc2Vjb3VycwogICAg"
        "ZWxpZiBzZXJpZToKICAgICAgICByZXN1bHRhdFsicG9wdWxhdGlvbl9hY3R1ZWxsZSJdID0gc2VyaWVbbWF4KHNlcmllKV0KICAg"
        "IHJldHVybiByZXN1bHRhdAoKCmRlZiBleHBvcnRlcl9qc29uKGNoZW1pbiwgZG9ubmVlcykgLT4gTm9uZToKICAgIHdpdGggb3Bl"
        "bihjaGVtaW4sICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBqc29uLmR1bXAoZG9ubmVlcywgZiwgZW5zdXJl"
        "X2FzY2lpPUZhbHNlLCBpbmRlbnQ9MikK"
    ),
    "dvf": (
        "IiIiRG9ubmVlcyBEVkYgZ2VvbG9jYWxpc2VlcyAodmVudGVzIHJlZWxsZW1lbnQgZW5yZWdpc3RyZWVzIHBhciBsYSBER0ZpUCku"
        "CgpGaWNoaWVycyBjb21tdW5hdXggcHVibGllcyBwYXIgZGF0YS5nb3V2LmZyIDoKaHR0cHM6Ly9maWxlcy5kYXRhLmdvdXYuZnIv"
        "Z2VvLWR2Zi9sYXRlc3QvY3N2Lzxhbm5lZT4vY29tbXVuZXMvPGRlcD4vPGNvZGVfaW5zZWU+LmNzdi5negoKQ2VzIGZpY2hpZXJz"
        "IHJlY2Vuc2VudCBsZXMgbXV0YXRpb25zIGVmZmVjdGl2ZW1lbnQgc2lnbmVlcyA6IGlscyBuZSBtZXN1cmVudCBwYXMKbCdpbnRl"
        "bnRpb24gZCdhY2hhdCBtYWlzIGxhIHRyYW5zYWN0aW9uIGFib3V0aWUuIEMnZXN0IGxhIGJhc2UgbGEgcGx1cyBmaWFibGUKZGlz"
        "cG9uaWJsZSBncmF0dWl0ZW1lbnQgcG91ciBlc3RpbWVyIGxlcyBwcml4IGV0IGxhIHJvdGF0aW9uIHBhciB0eXBvbG9naWUuCiIi"
        "Igpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFubm90YXRpb25zCgppbXBvcnQgZGF0ZXRpbWUgYXMgZHQKaW1wb3J0IHJlCgppbXBv"
        "cnQgbnVtcHkgYXMgbnAKaW1wb3J0IHBhbmRhcyBhcyBwZAoKZnJvbSAuY29uZmlnIGltcG9ydCAoCiAgICBEVkZfQkFTRSwKICAg"
        "IERWRl9DQUNIRSwKICAgIFBSSVhfTTJfTUFYLAogICAgUFJJWF9NMl9NSU4sCiAgICBTVVJGQUNFX01BWCwKICAgIFNVUkZBQ0Vf"
        "TUlOLAogICAgVkFMRVVSX01JTiwKKQpmcm9tIC5odHRwIGltcG9ydCBTb3VyY2VFcnJvciwgZ2V0CgpUWVBFU19QUklOQ0lQQVVY"
        "ID0gKCJBcHBhcnRlbWVudCIsICJNYWlzb24iKQpOQVRVUkVTX1JFVEVOVUVTID0gKCJWZW50ZSIsICJWZW50ZSBlbiBsJ8OpdGF0"
        "IGZ1dHVyIGQnYWNow6h2ZW1lbnQiLCAiVmVudGUgdGVycmFpbiDDoCBiw6J0aXIiKQoKX0FMSUFTID0gewogICAgImlkX211dGF0"
        "aW9uIjogciJeaWRfbXV0YXRpb24kIiwKICAgICJkYXRlX211dGF0aW9uIjogciJeZGF0ZV9tdXRhdGlvbiQiLAogICAgIm5hdHVy"
        "ZV9tdXRhdGlvbiI6IHIiXm5hdHVyZV9tdXRhdGlvbiQiLAogICAgInZhbGV1cl9mb25jaWVyZSI6IHIiXnZhbGV1cl9mb25jaWVy"
        "ZSQiLAogICAgImNvZGVfY29tbXVuZSI6IHIiXmNvZGVfY29tbXVuZSQiLAogICAgIm5vbV9jb21tdW5lIjogciJebm9tX2NvbW11"
        "bmUkIiwKICAgICJ0eXBlX2xvY2FsIjogciJedHlwZV9sb2NhbCQiLAogICAgInN1cmZhY2VfcmVlbGxlX2JhdGkiOiByIl5zdXJm"
        "YWNlX3JlZWxsZV9iYXRpJCIsCiAgICAibm9tYnJlX3BpZWNlc19wcmluY2lwYWxlcyI6IHIiXm5vbWJyZV9waWVjZXNfcHJpbmNp"
        "cGFsZXMkIiwKICAgICJzdXJmYWNlX3RlcnJhaW4iOiByIl5zdXJmYWNlX3RlcnJhaW4kIiwKICAgICJpZF9wYXJjZWxsZSI6IHIi"
        "XmlkX3BhcmNlbGxlJCIsCiAgICAiY29kZV9wb3N0YWwiOiByIl5jb2RlX3Bvc3RhbCQiLAogICAgImFkcmVzc2Vfbm9tX3ZvaWUi"
        "OiByIl5hZHJlc3NlX25vbV92b2llJCIsCn0KCgpkZWYgX3VybChjb2RlX2luc2VlOiBzdHIsIGFubmVlOiBpbnQpIC0+IHN0cjoK"
        "ICAgIGRlcCA9IGNvZGVfaW5zZWVbOjNdIGlmIGNvZGVfaW5zZWVbOjJdIGluICgiOTciLCAiOTgiKSBlbHNlIGNvZGVfaW5zZWVb"
        "OjJdCiAgICByZXR1cm4gZiJ7RFZGX0JBU0V9L3thbm5lZX0vY29tbXVuZXMve2RlcH0ve2NvZGVfaW5zZWV9LmNzdi5neiIKCgpk"
        "ZWYgdGVsZWNoYXJnZXJfYW5uZWUoY29kZV9pbnNlZTogc3RyLCBhbm5lZTogaW50LCBmb3JjZXI6IGJvb2wgPSBGYWxzZSkgLT4g"
        "cGQuRGF0YUZyYW1lIHwgTm9uZToKICAgICIiIlJlbnZvaWUgbGVzIG11dGF0aW9ucyBicnV0ZXMgZGUgbGEgY29tbXVuZSBwb3Vy"
        "IHVuZSBhbm5lZSwgb3UgTm9uZSBzaSBhYnNlbnRlLiIiIgogICAgY2FjaGUgPSBEVkZfQ0FDSEUgLyBmIntjb2RlX2luc2VlfV97"
        "YW5uZWV9LmNzdi5neiIKICAgIG1hcnF1ZXVyX2Fic2VudCA9IERWRl9DQUNIRSAvIGYie2NvZGVfaW5zZWV9X3thbm5lZX0uYWJz"
        "ZW50IgoKICAgIGlmIG5vdCBmb3JjZXIgYW5kIG1hcnF1ZXVyX2Fic2VudC5leGlzdHMoKToKICAgICAgICBhZ2UgPSBkdC5kYXRl"
        "dGltZS5ub3coKS50aW1lc3RhbXAoKSAtIG1hcnF1ZXVyX2Fic2VudC5zdGF0KCkuc3RfbXRpbWUKICAgICAgICBpZiBhZ2UgPCA3"
        "ICogMjQgKiAzNjAwOgogICAgICAgICAgICByZXR1cm4gTm9uZQoKICAgIGlmIGZvcmNlciBvciBub3QgY2FjaGUuZXhpc3RzKCk6"
        "CiAgICAgICAgcmVwb25zZSA9IGdldChfdXJsKGNvZGVfaW5zZWUsIGFubmVlKSwgc3RyZWFtPVRydWUpCiAgICAgICAgaWYgcmVw"
        "b25zZS5zdGF0dXNfY29kZSA9PSA0MDQ6CiAgICAgICAgICAgIG1hcnF1ZXVyX2Fic2VudC50b3VjaCgpCiAgICAgICAgICAgIHJl"
        "dHVybiBOb25lCiAgICAgICAgaWYgcmVwb25zZS5zdGF0dXNfY29kZSAhPSAyMDA6CiAgICAgICAgICAgIHJhaXNlIFNvdXJjZUVy"
        "cm9yKGYiRFZGIHthbm5lZX0gOiByZXBvbnNlIHtyZXBvbnNlLnN0YXR1c19jb2RlfSIpCiAgICAgICAgY2FjaGUud3JpdGVfYnl0"
        "ZXMocmVwb25zZS5jb250ZW50KQoKICAgIHRyeToKICAgICAgICBkZiA9IHBkLnJlYWRfY3N2KGNhY2hlLCBjb21wcmVzc2lvbj0i"
        "Z3ppcCIsIGR0eXBlPXN0ciwgbG93X21lbW9yeT1GYWxzZSkKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOiAgIyBmaWNoaWVy"
        "IHRyb25xdWUgb3UgY29ycm9tcHUgOiBvbiByZXBhcnQgZHUgcmVzZWF1CiAgICAgICAgY2FjaGUudW5saW5rKG1pc3Npbmdfb2s9"
        "VHJ1ZSkKICAgICAgICByYWlzZSBTb3VyY2VFcnJvcihmIkZpY2hpZXIgRFZGIHthbm5lZX0gaWxsaXNpYmxlICh7ZXhjfSkiKSBm"
        "cm9tIGV4YwogICAgcmV0dXJuIGRmCgoKZGVmIGFubmVlc19kaXNwb25pYmxlcyhjb2RlX2luc2VlOiBzdHIsIHByb2ZvbmRldXI6"
        "IGludCA9IDYpIC0+IGxpc3RbaW50XToKICAgICIiIkFubmVlcyBEVkYgcmVlbGxlbWVudCBwdWJsaWVlcyBwb3VyIGNldHRlIGNv"
        "bW11bmUsIGRlIGxhIHBsdXMgYW5jaWVubmUgYSBsYSBwbHVzIHJlY2VudGUuIiIiCiAgICBjb3VyYW50ZSA9IGR0LmRhdGUudG9k"
        "YXkoKS55ZWFyCiAgICB0cm91dmVlczogbGlzdFtpbnRdID0gW10KICAgIGVycmV1cnM6IGxpc3Rbc3RyXSA9IFtdCiAgICBmb3Ig"
        "YW5uZWUgaW4gcmFuZ2UoY291cmFudGUsIGNvdXJhbnRlIC0gcHJvZm9uZGV1ciAtIDEsIC0xKToKICAgICAgICB0cnk6CiAgICAg"
        "ICAgICAgIGRmID0gdGVsZWNoYXJnZXJfYW5uZWUoY29kZV9pbnNlZSwgYW5uZWUpCiAgICAgICAgZXhjZXB0IFNvdXJjZUVycm9y"
        "IGFzIGV4YzoKICAgICAgICAgICAgZXJyZXVycy5hcHBlbmQoZiJ7YW5uZWV9OiB7ZXhjfSIpCiAgICAgICAgICAgIGNvbnRpbnVl"
        "CiAgICAgICAgaWYgZGYgaXMgbm90IE5vbmUgYW5kIGxlbihkZik6CiAgICAgICAgICAgIHRyb3V2ZWVzLmFwcGVuZChhbm5lZSkK"
        "ICAgIGlmIG5vdCB0cm91dmVlcyBhbmQgZXJyZXVyczoKICAgICAgICByYWlzZSBTb3VyY2VFcnJvcigiU2VydmV1ciBEVkYgaW5q"
        "b2lnbmFibGUg4oCUICIgKyAiIHwgIi5qb2luKGVycmV1cnNbOjNdKSkKICAgIHJldHVybiBzb3J0ZWQodHJvdXZlZXMpCgoKZGVm"
        "IF9tYXBwZXJfY29sb25uZXMoZGY6IHBkLkRhdGFGcmFtZSkgLT4gZGljdFtzdHIsIHN0cl06CiAgICBjb3JyZXNwb25kYW5jZXMg"
        "PSB7fQogICAgZm9yIGNpYmxlLCBtb3RpZiBpbiBfQUxJQVMuaXRlbXMoKToKICAgICAgICBmb3IgY29sb25uZSBpbiBkZi5jb2x1"
        "bW5zOgogICAgICAgICAgICBpZiByZS5tYXRjaChtb3RpZiwgY29sb25uZS5zdHJpcCgpLCBmbGFncz1yZS5JKToKICAgICAgICAg"
        "ICAgICAgIGNvcnJlc3BvbmRhbmNlc1tjaWJsZV0gPSBjb2xvbm5lCiAgICAgICAgICAgICAgICBicmVhawogICAgcmV0dXJuIGNv"
        "cnJlc3BvbmRhbmNlcwoKCmRlZiBjaGFyZ2VyKGNvZGVfaW5zZWU6IHN0ciwgYW5uZWVzOiBsaXN0W2ludF0gfCBOb25lID0gTm9u"
        "ZSkgLT4gcGQuRGF0YUZyYW1lOgogICAgIiIiQ29uY2F0ZW5lIGxlcyBtdXRhdGlvbnMgYnJ1dGVzIGRlIGxhIGNvbW11bmUgc3Vy"
        "IGxlcyBhbm5lZXMgZGVtYW5kZWVzLiIiIgogICAgYW5uZWVzID0gYW5uZWVzIG9yIGFubmVlc19kaXNwb25pYmxlcyhjb2RlX2lu"
        "c2VlKQogICAgbW9yY2VhdXggPSBbXQogICAgZm9yIGFubmVlIGluIGFubmVlczoKICAgICAgICBkZiA9IHRlbGVjaGFyZ2VyX2Fu"
        "bmVlKGNvZGVfaW5zZWUsIGFubmVlKQogICAgICAgIGlmIGRmIGlzIE5vbmUgb3IgZGYuZW1wdHk6CiAgICAgICAgICAgIGNvbnRp"
        "bnVlCiAgICAgICAgZGYgPSBkZi5jb3B5KCkKICAgICAgICBkZlsiYW5uZWVfZmljaGllciJdID0gYW5uZWUKICAgICAgICBtb3Jj"
        "ZWF1eC5hcHBlbmQoZGYpCiAgICBpZiBub3QgbW9yY2VhdXg6CiAgICAgICAgcmFpc2UgU291cmNlRXJyb3IoCiAgICAgICAgICAg"
        "ICJBdWN1bmUgZG9ubmVlIERWRiBwb3VyIGNldHRlIGNvbW11bmUuICIKICAgICAgICAgICAgIkwnQWxzYWNlLU1vc2VsbGUgKDU3"
        "LCA2NywgNjgpIGV0IE1heW90dGUgbmUgc29udCBwYXMgY291dmVydGVzIHBhciBEVkYuIgogICAgICAgICkKICAgIHJldHVybiBw"
        "ZC5jb25jYXQobW9yY2VhdXgsIGlnbm9yZV9pbmRleD1UcnVlKQoKCmRlZiBwcmVwYXJlcihicnV0OiBwZC5EYXRhRnJhbWUpIC0+"
        "IHBkLkRhdGFGcmFtZToKICAgICIiIk5ldHRvaWUgbGVzIG11dGF0aW9ucyBldCBuZSBjb25zZXJ2ZSBxdWUgbGVzIHZlbnRlcyBk"
        "J3VuIHNldWwgbG9nZW1lbnQuCgogICAgVW5lIG11dGF0aW9uIERWRiBlc3QgZWNsYXRlZSBlbiBwbHVzaWV1cnMgbGlnbmVzIChs"
        "b3RzLCBwYXJjZWxsZXMsIGRlcGVuZGFuY2VzKS4KICAgIE9uIGlzb2xlIGxlcyB2ZW50ZXMgcG9ydGFudCBzdXIgdW4gdW5pcXVl"
        "IGxvZ2VtZW50IDogYydlc3QgbGEgbWFpbGxlIHBlcnRpbmVudGUKICAgIHBvdXIgdW4gcHJpeCBhdSBtMiBldCBwb3VyIGwnYW5h"
        "bHlzZSBwYXIgdHlwb2xvZ2llLgogICAgIiIiCiAgICBjb2xzID0gX21hcHBlcl9jb2xvbm5lcyhicnV0KQogICAgb2JsaWdhdG9p"
        "cmVzID0gWyJpZF9tdXRhdGlvbiIsICJkYXRlX211dGF0aW9uIiwgInZhbGV1cl9mb25jaWVyZSIsICJ0eXBlX2xvY2FsIiwgInN1"
        "cmZhY2VfcmVlbGxlX2JhdGkiXQogICAgbWFucXVhbnRlcyA9IFtjIGZvciBjIGluIG9ibGlnYXRvaXJlcyBpZiBjIG5vdCBpbiBj"
        "b2xzXQogICAgaWYgbWFucXVhbnRlczoKICAgICAgICByYWlzZSBTb3VyY2VFcnJvcihmIkNvbG9ubmVzIERWRiBpbmF0dGVuZHVl"
        "cywgY2hhbXBzIG1hbnF1YW50cyA6IHttYW5xdWFudGVzfSIpCgogICAgZGYgPSBicnV0LnJlbmFtZShjb2x1bW5zPXt2OiBrIGZv"
        "ciBrLCB2IGluIGNvbHMuaXRlbXMoKX0pLmNvcHkoKQogICAgZm9yIGNvbG9ubmUgaW4gKCJ2YWxldXJfZm9uY2llcmUiLCAic3Vy"
        "ZmFjZV9yZWVsbGVfYmF0aSIsICJub21icmVfcGllY2VzX3ByaW5jaXBhbGVzIiwgInN1cmZhY2VfdGVycmFpbiIpOgogICAgICAg"
        "IGlmIGNvbG9ubmUgaW4gZGYuY29sdW1uczoKICAgICAgICAgICAgZGZbY29sb25uZV0gPSBwZC50b19udW1lcmljKGRmW2NvbG9u"
        "bmVdLmFzdHlwZShzdHIpLnN0ci5yZXBsYWNlKCIsIiwgIi4iLCByZWdleD1GYWxzZSksIGVycm9ycz0iY29lcmNlIikKICAgICAg"
        "ICBlbHNlOgogICAgICAgICAgICBkZltjb2xvbm5lXSA9IG5wLm5hbgogICAgZGZbImRhdGVfbXV0YXRpb24iXSA9IHBkLnRvX2Rh"
        "dGV0aW1lKGRmWyJkYXRlX211dGF0aW9uIl0sIGVycm9ycz0iY29lcmNlIikKICAgIGRmID0gZGYuZHJvcG5hKHN1YnNldD1bImRh"
        "dGVfbXV0YXRpb24iLCAidmFsZXVyX2ZvbmNpZXJlIiwgImlkX211dGF0aW9uIl0pCgogICAgaWYgIm5hdHVyZV9tdXRhdGlvbiIg"
        "aW4gZGYuY29sdW1uczoKICAgICAgICBkZiA9IGRmW2RmWyJuYXR1cmVfbXV0YXRpb24iXS5pc2luKE5BVFVSRVNfUkVURU5VRVMp"
        "XQoKICAgIHByaW5jaXBhdXggPSBkZltkZlsidHlwZV9sb2NhbCJdLmlzaW4oVFlQRVNfUFJJTkNJUEFVWCldLmNvcHkoKQogICAg"
        "aWYgcHJpbmNpcGF1eC5lbXB0eToKICAgICAgICByZXR1cm4gcHJpbmNpcGF1eC5hc3NpZ24ocHJpeF9tMj1bXSwgc2VnbWVudD1b"
        "XSwgYW5uZWU9W10pCgogICAgIyBVbmUgbGlnbmUgcGFyIGxvZ2VtZW50IGRpc3RpbmN0IGF1IHNlaW4gZCd1bmUgbXV0YXRpb24u"
        "CiAgICBwcmluY2lwYXV4ID0gcHJpbmNpcGF1eC5kcm9wX2R1cGxpY2F0ZXMoCiAgICAgICAgc3Vic2V0PVsiaWRfbXV0YXRpb24i"
        "LCAidHlwZV9sb2NhbCIsICJzdXJmYWNlX3JlZWxsZV9iYXRpIiwgIm5vbWJyZV9waWVjZXNfcHJpbmNpcGFsZXMiXQogICAgKQog"
        "ICAgbmJfbG9nZW1lbnRzID0gcHJpbmNpcGF1eC5ncm91cGJ5KCJpZF9tdXRhdGlvbiIpWyJ0eXBlX2xvY2FsIl0uc2l6ZSgpLnJl"
        "bmFtZSgibmJfbG9nZW1lbnRzIikKICAgIHByaW5jaXBhdXggPSBwcmluY2lwYXV4LmpvaW4obmJfbG9nZW1lbnRzLCBvbj0iaWRf"
        "bXV0YXRpb24iKQogICAgcHJpbmNpcGF1eCA9IHByaW5jaXBhdXhbcHJpbmNpcGF1eFsibmJfbG9nZW1lbnRzIl0gPT0gMV0uY29w"
        "eSgpCgogICAgIyBUZXJyYWluIDogc29tbWUgZGVzIHBhcmNlbGxlcyBkaXN0aW5jdGVzIGRlIGxhIG11dGF0aW9uICh1dGlsZSBw"
        "b3VyIGxlcyBtYWlzb25zKS4KICAgIGlmICJpZF9wYXJjZWxsZSIgaW4gZGYuY29sdW1uczoKICAgICAgICB0ZXJyYWlucyA9ICgK"
        "ICAgICAgICAgICAgZGYuZHJvcG5hKHN1YnNldD1bInN1cmZhY2VfdGVycmFpbiJdKQogICAgICAgICAgICAuZHJvcF9kdXBsaWNh"
        "dGVzKHN1YnNldD1bImlkX211dGF0aW9uIiwgImlkX3BhcmNlbGxlIl0pCiAgICAgICAgICAgIC5ncm91cGJ5KCJpZF9tdXRhdGlv"
        "biIpWyJzdXJmYWNlX3RlcnJhaW4iXQogICAgICAgICAgICAuc3VtKCkKICAgICAgICAgICAgLnJlbmFtZSgidGVycmFpbl90b3Rh"
        "bCIpCiAgICAgICAgKQogICAgICAgIHByaW5jaXBhdXggPSBwcmluY2lwYXV4LmpvaW4odGVycmFpbnMsIG9uPSJpZF9tdXRhdGlv"
        "biIpCiAgICBlbHNlOgogICAgICAgIHByaW5jaXBhdXhbInRlcnJhaW5fdG90YWwiXSA9IG5wLm5hbgoKICAgICMgUHJlc2VuY2Ug"
        "ZCd1bmUgZGVwZW5kYW5jZSB2ZW5kdWUgYXZlYyBsZSBsb2dlbWVudCAoZ2FyYWdlLCBjYXZlLCBib3gpLgogICAgZGVwZW5kYW5j"
        "ZXMgPSAoCiAgICAgICAgZGZbZGZbInR5cGVfbG9jYWwiXS5hc3R5cGUoc3RyKS5zdHIuc3RhcnRzd2l0aCgiRCIsIG5hPUZhbHNl"
        "KV0KICAgICAgICAuZ3JvdXBieSgiaWRfbXV0YXRpb24iKQogICAgICAgIC5zaXplKCkKICAgICAgICAucmVuYW1lKCJuYl9kZXBl"
        "bmRhbmNlcyIpCiAgICApCiAgICBwcmluY2lwYXV4ID0gcHJpbmNpcGF1eC5qb2luKGRlcGVuZGFuY2VzLCBvbj0iaWRfbXV0YXRp"
        "b24iKQogICAgcHJpbmNpcGF1eFsibmJfZGVwZW5kYW5jZXMiXSA9IHByaW5jaXBhdXhbIm5iX2RlcGVuZGFuY2VzIl0uZmlsbG5h"
        "KDApLmFzdHlwZShpbnQpCgogICAgcHJpbmNpcGF1eCA9IHByaW5jaXBhdXhbCiAgICAgICAgKHByaW5jaXBhdXhbInN1cmZhY2Vf"
        "cmVlbGxlX2JhdGkiXS5iZXR3ZWVuKFNVUkZBQ0VfTUlOLCBTVVJGQUNFX01BWCkpCiAgICAgICAgJiAocHJpbmNpcGF1eFsidmFs"
        "ZXVyX2ZvbmNpZXJlIl0gPj0gVkFMRVVSX01JTikKICAgIF0uY29weSgpCiAgICBwcmluY2lwYXV4WyJwcml4X20yIl0gPSBwcmlu"
        "Y2lwYXV4WyJ2YWxldXJfZm9uY2llcmUiXSAvIHByaW5jaXBhdXhbInN1cmZhY2VfcmVlbGxlX2JhdGkiXQogICAgcHJpbmNpcGF1"
        "eCA9IHByaW5jaXBhdXhbcHJpbmNpcGF1eFsicHJpeF9tMiJdLmJldHdlZW4oUFJJWF9NMl9NSU4sIFBSSVhfTTJfTUFYKV0KCiAg"
        "ICBwcmluY2lwYXV4WyJhbm5lZSJdID0gcHJpbmNpcGF1eFsiZGF0ZV9tdXRhdGlvbiJdLmR0LnllYXIKICAgIHByaW5jaXBhdXhb"
        "InBpZWNlcyJdID0gcHJpbmNpcGF1eFsibm9tYnJlX3BpZWNlc19wcmluY2lwYWxlcyJdLmZpbGxuYSgwKS5hc3R5cGUoaW50KQog"
        "ICAgcHJpbmNpcGF1eFsic2VnbWVudCJdID0gWwogICAgICAgIF9zZWdtZW50KHQsIHApIGZvciB0LCBwIGluIHppcChwcmluY2lw"
        "YXV4WyJ0eXBlX2xvY2FsIl0sIHByaW5jaXBhdXhbInBpZWNlcyJdKQogICAgXQogICAgcmV0dXJuIHByaW5jaXBhdXgucmVzZXRf"
        "aW5kZXgoZHJvcD1UcnVlKQoKCmRlZiBfc2VnbWVudCh0eXBlX2xvY2FsOiBzdHIsIHBpZWNlczogaW50KSAtPiBzdHI6CiAgICBp"
        "ZiB0eXBlX2xvY2FsID09ICJBcHBhcnRlbWVudCI6CiAgICAgICAgaWYgcGllY2VzIDw9IDA6CiAgICAgICAgICAgIHJldHVybiAi"
        "QXBwYXJ0ZW1lbnQgKHBpZWNlcyBub24gcmVuc2VpZ25lZXMpIgogICAgICAgIGlmIHBpZWNlcyA+PSA1OgogICAgICAgICAgICBy"
        "ZXR1cm4gIkFwcGFydGVtZW50IFQ1IGV0ICsiCiAgICAgICAgcmV0dXJuIGYiQXBwYXJ0ZW1lbnQgVHtwaWVjZXN9IgogICAgaWYg"
        "cGllY2VzIDw9IDA6CiAgICAgICAgcmV0dXJuICJNYWlzb24gKHBpZWNlcyBub24gcmVuc2VpZ25lZXMpIgogICAgaWYgcGllY2Vz"
        "IDw9IDM6CiAgICAgICAgcmV0dXJuICJNYWlzb24gMS0zIHBpZWNlcyIKICAgIGlmIHBpZWNlcyA+PSA2OgogICAgICAgIHJldHVy"
        "biAiTWFpc29uIDYgcGllY2VzIGV0ICsiCiAgICByZXR1cm4gZiJNYWlzb24ge3BpZWNlc30gcGllY2VzIgoKCmRlZiBwcml4X3Bh"
        "cl9hbm5lZSh2ZW50ZXM6IHBkLkRhdGFGcmFtZSkgLT4gcGQuRGF0YUZyYW1lOgogICAgIiIiUHJpeCBtZWRpYW4gZXQgbW95ZW4g"
        "YXUgbTIsIHBhciBhbm5lZSBldCBwYXIgdHlwZSBkZSBiaWVuLiIiIgogICAgaWYgdmVudGVzLmVtcHR5OgogICAgICAgIHJldHVy"
        "biBwZC5EYXRhRnJhbWUoKQogICAgbGlnbmVzID0gW10KICAgIGZvciBhbm5lZSwgYmxvYyBpbiB2ZW50ZXMuZ3JvdXBieSgiYW5u"
        "ZWUiKToKICAgICAgICBsaWduZSA9IHsKICAgICAgICAgICAgImFubmVlIjogaW50KGFubmVlKSwKICAgICAgICAgICAgInZlbnRl"
        "cyI6IGxlbihibG9jKSwKICAgICAgICAgICAgInByaXhfbTJfbWVkaWFuIjogYmxvY1sicHJpeF9tMiJdLm1lZGlhbigpLAogICAg"
        "ICAgICAgICAicHJpeF9tMl9tb3llbiI6IGJsb2NbInByaXhfbTIiXS5tZWFuKCksCiAgICAgICAgICAgICJwcml4X21lZGlhbiI6"
        "IGJsb2NbInZhbGV1cl9mb25jaWVyZSJdLm1lZGlhbigpLAogICAgICAgICAgICAic3VyZmFjZV9tZWRpYW5lIjogYmxvY1sic3Vy"
        "ZmFjZV9yZWVsbGVfYmF0aSJdLm1lZGlhbigpLAogICAgICAgIH0KICAgICAgICBmb3IgdHlwZV9sb2NhbCBpbiBUWVBFU19QUklO"
        "Q0lQQVVYOgogICAgICAgICAgICBzb3VzID0gYmxvY1tibG9jWyJ0eXBlX2xvY2FsIl0gPT0gdHlwZV9sb2NhbF0KICAgICAgICAg"
        "ICAgY2xlID0gdHlwZV9sb2NhbC5sb3dlcigpCiAgICAgICAgICAgIGxpZ25lW2YidmVudGVzX3tjbGV9Il0gPSBsZW4oc291cykK"
        "ICAgICAgICAgICAgbGlnbmVbZiJwcml4X20yX21lZGlhbl97Y2xlfSJdID0gc291c1sicHJpeF9tMiJdLm1lZGlhbigpIGlmIGxl"
        "bihzb3VzKSA+PSAzIGVsc2UgbnAubmFuCiAgICAgICAgbGlnbmVzLmFwcGVuZChsaWduZSkKICAgIHJldHVybiBwZC5EYXRhRnJh"
        "bWUobGlnbmVzKS5zb3J0X3ZhbHVlcygiYW5uZWUiKS5yZXNldF9pbmRleChkcm9wPVRydWUpCgoKZGVmIGV2b2x1dGlvbl9wcml4"
        "KHRhYmxlX2FubnVlbGxlOiBwZC5EYXRhRnJhbWUsIHJlY3VsOiBpbnQgPSAzLCBjb2xvbm5lOiBzdHIgPSAicHJpeF9tMl9tZWRp"
        "YW4iKSAtPiBkaWN0IHwgTm9uZToKICAgICIiIlZhcmlhdGlvbiBkdSBwcml4IGF1IG0yIGVudHJlIGxhIGRlcm5pZXJlIGFubmVl"
        "IGNvbXBsZXRlIGV0IE4gYW5uZWVzIHBsdXMgdG90LiIiIgogICAgaWYgdGFibGVfYW5udWVsbGUgaXMgTm9uZSBvciB0YWJsZV9h"
        "bm51ZWxsZS5lbXB0eToKICAgICAgICByZXR1cm4gTm9uZQogICAgdGFibGUgPSB0YWJsZV9hbm51ZWxsZS5kcm9wbmEoc3Vic2V0"
        "PVtjb2xvbm5lXSkKICAgIHRhYmxlID0gdGFibGVbdGFibGVbInZlbnRlcyJdID49IDVdCiAgICBpZiBsZW4odGFibGUpIDwgMjoK"
        "ICAgICAgICByZXR1cm4gTm9uZQogICAgZmluID0gaW50KHRhYmxlWyJhbm5lZSJdLm1heCgpKQogICAgY2FuZGlkYXRlcyA9IHRh"
        "YmxlW3RhYmxlWyJhbm5lZSJdIDw9IGZpbiAtIHJlY3VsXQogICAgZGVidXQgPSBpbnQoY2FuZGlkYXRlc1siYW5uZWUiXS5tYXgo"
        "KSkgaWYgbGVuKGNhbmRpZGF0ZXMpIGVsc2UgaW50KHRhYmxlWyJhbm5lZSJdLm1pbigpKQogICAgaWYgZGVidXQgPT0gZmluOgog"
        "ICAgICAgIHJldHVybiBOb25lCiAgICB2X2RlYnV0ID0gZmxvYXQodGFibGUubG9jW3RhYmxlWyJhbm5lZSJdID09IGRlYnV0LCBj"
        "b2xvbm5lXS5pbG9jWzBdKQogICAgdl9maW4gPSBmbG9hdCh0YWJsZS5sb2NbdGFibGVbImFubmVlIl0gPT0gZmluLCBjb2xvbm5l"
        "XS5pbG9jWzBdKQogICAgZHVyZWUgPSBmaW4gLSBkZWJ1dAogICAgcmV0dXJuIHsKICAgICAgICAiYW5uZWVfZGVidXQiOiBkZWJ1"
        "dCwKICAgICAgICAiYW5uZWVfZmluIjogZmluLAogICAgICAgICJ2YWxldXJfZGVidXQiOiB2X2RlYnV0LAogICAgICAgICJ2YWxl"
        "dXJfZmluIjogdl9maW4sCiAgICAgICAgInZhcmlhdGlvbl9wY3QiOiAodl9maW4gLSB2X2RlYnV0KSAvIHZfZGVidXQgKiAxMDAg"
        "aWYgdl9kZWJ1dCBlbHNlIE5vbmUsCiAgICAgICAgInRjYW1fcGN0IjogKCh2X2ZpbiAvIHZfZGVidXQpICoqICgxIC8gZHVyZWUp"
        "IC0gMSkgKiAxMDAgaWYgdl9kZWJ1dCBhbmQgZHVyZWUgZWxzZSBOb25lLAogICAgICAgICJkdXJlZSI6IGR1cmVlLAogICAgfQoK"
        "CmRlZiBwZXJpb2RlX3JlY2VudGUodmVudGVzOiBwZC5EYXRhRnJhbWUsIG1vaXM6IGludCA9IDI0KSAtPiBwZC5EYXRhRnJhbWU6"
        "CiAgICAiIiJWZW50ZXMgZGVzIE4gZGVybmllcnMgbW9pcyBjb3V2ZXJ0cyBwYXIgbGVzIGRvbm5lZXMuIiIiCiAgICBpZiB2ZW50"
        "ZXMuZW1wdHk6CiAgICAgICAgcmV0dXJuIHZlbnRlcwogICAgZmluID0gdmVudGVzWyJkYXRlX211dGF0aW9uIl0ubWF4KCkKICAg"
        "IGRlYnV0ID0gZmluIC0gcGQuRGF0ZU9mZnNldChtb250aHM9bW9pcykKICAgIHJldHVybiB2ZW50ZXNbdmVudGVzWyJkYXRlX211"
        "dGF0aW9uIl0gPiBkZWJ1dF0KCgpkZWYgY291dmVydHVyZSh2ZW50ZXM6IHBkLkRhdGFGcmFtZSkgLT4gZGljdDoKICAgIGlmIHZl"
        "bnRlcy5lbXB0eToKICAgICAgICByZXR1cm4ge30KICAgIHJldHVybiB7CiAgICAgICAgImRlYnV0IjogdmVudGVzWyJkYXRlX211"
        "dGF0aW9uIl0ubWluKCkuZGF0ZSgpLAogICAgICAgICJmaW4iOiB2ZW50ZXNbImRhdGVfbXV0YXRpb24iXS5tYXgoKS5kYXRlKCks"
        "CiAgICAgICAgInZlbnRlcyI6IGludChsZW4odmVudGVzKSksCiAgICB9Cg=="
    ),
    "demande": (
        "IiIiRXN0aW1hdGlvbiBkZSBsYSBkZW1hbmRlIHBhciB0eXBvbG9naWUgYSBwYXJ0aXIgZGVzIHZlbnRlcyBEVkYuCgpBdWN1bmUg"
        "YmFzZSBwdWJsaXF1ZSBuZSBtZXN1cmUgbGEgZGVtYW5kZSBhdSBzZW5zIGRlcyBhY2hldGV1cnMgZW4gcmVjaGVyY2hlLgpMJ2Fw"
        "cHJvY2hlIHJldGVudWUgOiB1bmUgdHlwb2xvZ2llIGVzdCBkJ2F1dGFudCBwbHVzIGRlbWFuZGVlIHF1J2VsbGUgc2UgdmVuZApl"
        "biB2b2x1bWUsIHF1ZSBjZSB2b2x1bWUgcHJvZ3Jlc3NlIGV0IHF1ZSBzb24gcHJpeCBhdSBtMiBwcm9ncmVzc2UuIExlcyB0cm9p"
        "cwpzaWduYXV4IHNvbnQgY29tYmluZXMgZW4gdW4gc2NvcmUgZGUgMCBhIDEwMCwgYSBsaXJlIGNvbW1lIHVuIGNsYXNzZW1lbnQK"
        "cmVsYXRpZiBhdSBzZWluIGRlIGxhIGNvbW11bmUsIGphbWFpcyBjb21tZSB1bmUgbWVzdXJlIGFic29sdWUuCiIiIgpmcm9tIF9f"
        "ZnV0dXJlX18gaW1wb3J0IGFubm90YXRpb25zCgppbXBvcnQgbnVtcHkgYXMgbnAKaW1wb3J0IHBhbmRhcyBhcyBwZAoKZnJvbSAu"
        "ZHZmIGltcG9ydCBwZXJpb2RlX3JlY2VudGUKClBPTkRFUkFUSU9OUyA9IHsKICAgICJwYXJ0X21hcmNoZSI6IDAuNDAsCiAgICAi"
        "ZXZvbHV0aW9uX3ZvbHVtZSI6IDAuMjUsCiAgICAiZXZvbHV0aW9uX3ByaXgiOiAwLjI1LAogICAgInZvbHVtZV9hYnNvbHUiOiAw"
        "LjEwLAp9CgoKZGVmIF9yYW5nX25vcm1hbGlzZShzZXJpZTogcGQuU2VyaWVzKSAtPiBwZC5TZXJpZXM6CiAgICAiIiJDbGFzc2Vt"
        "ZW50IDAtMSByb2J1c3RlIChpbnNlbnNpYmxlIGF1eCB2YWxldXJzIGV4dHJlbWVzKS4iIiIKICAgIHZhbGlkZSA9IHNlcmllLmRy"
        "b3BuYSgpCiAgICBpZiB2YWxpZGUuZW1wdHk6CiAgICAgICAgcmV0dXJuIHBkLlNlcmllcyhucC5uYW4sIGluZGV4PXNlcmllLmlu"
        "ZGV4KQogICAgaWYgdmFsaWRlLm51bmlxdWUoKSA9PSAxOgogICAgICAgIHJldHVybiBwZC5TZXJpZXMobnAud2hlcmUoc2VyaWUu"
        "bm90bmEoKSwgMC41LCBucC5uYW4pLCBpbmRleD1zZXJpZS5pbmRleCkKICAgIHJhbmdzID0gc2VyaWUucmFuayhtZXRob2Q9ImF2"
        "ZXJhZ2UiLCBuYV9vcHRpb249ImtlZXAiKQogICAgcmV0dXJuIChyYW5ncyAtIHJhbmdzLm1pbigpKSAvIChyYW5ncy5tYXgoKSAt"
        "IHJhbmdzLm1pbigpKQoKCmRlZiBfZXZvbHV0aW9uX3ByaXhfc2VnbWVudCh2ZW50ZXM6IHBkLkRhdGFGcmFtZSwgc2VnbWVudDog"
        "c3RyLCByZWN1bDogaW50ID0gMywgbWluaTogaW50ID0gMykgLT4gZmxvYXQgfCBOb25lOgogICAgc291cyA9IHZlbnRlc1t2ZW50"
        "ZXNbInNlZ21lbnQiXSA9PSBzZWdtZW50XQogICAgaWYgc291cy5lbXB0eToKICAgICAgICByZXR1cm4gTm9uZQogICAgcGFyX2Fu"
        "bmVlID0gc291cy5ncm91cGJ5KCJhbm5lZSIpLmFnZyhuPSgicHJpeF9tMiIsICJzaXplIiksIG1lZGlhbj0oInByaXhfbTIiLCAi"
        "bWVkaWFuIikpCiAgICBwYXJfYW5uZWUgPSBwYXJfYW5uZWVbcGFyX2FubmVlWyJuIl0gPj0gbWluaV0KICAgIGlmIGxlbihwYXJf"
        "YW5uZWUpIDwgMjoKICAgICAgICByZXR1cm4gTm9uZQogICAgZmluID0gaW50KHBhcl9hbm5lZS5pbmRleC5tYXgoKSkKICAgIGNh"
        "bmRpZGF0ZXMgPSBbYSBmb3IgYSBpbiBwYXJfYW5uZWUuaW5kZXggaWYgYSA8PSBmaW4gLSByZWN1bF0KICAgIGRlYnV0ID0gaW50"
        "KG1heChjYW5kaWRhdGVzKSkgaWYgY2FuZGlkYXRlcyBlbHNlIGludChwYXJfYW5uZWUuaW5kZXgubWluKCkpCiAgICBpZiBkZWJ1"
        "dCA9PSBmaW46CiAgICAgICAgcmV0dXJuIE5vbmUKICAgIHZfZGVidXQgPSBmbG9hdChwYXJfYW5uZWUubG9jW2RlYnV0LCAibWVk"
        "aWFuIl0pCiAgICB2X2ZpbiA9IGZsb2F0KHBhcl9hbm5lZS5sb2NbZmluLCAibWVkaWFuIl0pCiAgICByZXR1cm4gKHZfZmluIC0g"
        "dl9kZWJ1dCkgLyB2X2RlYnV0ICogMTAwIGlmIHZfZGVidXQgZWxzZSBOb25lCgoKZGVmIGFuYWx5c2VyKHZlbnRlczogcGQuRGF0"
        "YUZyYW1lLCBtb2lzOiBpbnQgPSAyNCwgc2V1aWxfdmVudGVzOiBpbnQgPSA1KSAtPiBwZC5EYXRhRnJhbWU6CiAgICAiIiJUYWJs"
        "ZWF1IGRlIGxhIGRlbWFuZGUgcGFyIHR5cG9sb2dpZS4iIiIKICAgIGlmIHZlbnRlcy5lbXB0eToKICAgICAgICByZXR1cm4gcGQu"
        "RGF0YUZyYW1lKCkKCiAgICByZWNlbnRlcyA9IHBlcmlvZGVfcmVjZW50ZSh2ZW50ZXMsIG1vaXMpCiAgICBmaW4gPSB2ZW50ZXNb"
        "ImRhdGVfbXV0YXRpb24iXS5tYXgoKQogICAgZGVidXRfcmVjZW50ID0gZmluIC0gcGQuRGF0ZU9mZnNldChtb250aHM9bW9pcykK"
        "ICAgIHByZWNlZGVudGVzID0gdmVudGVzWwogICAgICAgICh2ZW50ZXNbImRhdGVfbXV0YXRpb24iXSA8PSBkZWJ1dF9yZWNlbnQp"
        "CiAgICAgICAgJiAodmVudGVzWyJkYXRlX211dGF0aW9uIl0gPiBkZWJ1dF9yZWNlbnQgLSBwZC5EYXRlT2Zmc2V0KG1vbnRocz1t"
        "b2lzKSkKICAgIF0KCiAgICB0b3RhbF9yZWNlbnQgPSBsZW4ocmVjZW50ZXMpCiAgICBsaWduZXMgPSBbXQogICAgZm9yIHNlZ21l"
        "bnQsIGJsb2MgaW4gcmVjZW50ZXMuZ3JvdXBieSgic2VnbWVudCIpOgogICAgICAgIGFudGVyaWV1ciA9IGxlbihwcmVjZWRlbnRl"
        "c1twcmVjZWRlbnRlc1sic2VnbWVudCJdID09IHNlZ21lbnRdKQogICAgICAgIGV2b192b2x1bWUgPSAoKGxlbihibG9jKSAtIGFu"
        "dGVyaWV1cikgLyBhbnRlcmlldXIgKiAxMDApIGlmIGFudGVyaWV1ciA+PSAzIGVsc2UgbnAubmFuCiAgICAgICAgbGlnbmVzLmFw"
        "cGVuZCgKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgInNlZ21lbnQiOiBzZWdtZW50LAogICAgICAgICAgICAgICAgInR5"
        "cGUiOiBibG9jWyJ0eXBlX2xvY2FsIl0uaWxvY1swXSwKICAgICAgICAgICAgICAgICJ2ZW50ZXNfcmVjZW50ZXMiOiBsZW4oYmxv"
        "YyksCiAgICAgICAgICAgICAgICAidmVudGVzX3BlcmlvZGVfcHJlY2VkZW50ZSI6IGFudGVyaWV1ciwKICAgICAgICAgICAgICAg"
        "ICJwYXJ0X21hcmNoZV9wY3QiOiBsZW4oYmxvYykgLyB0b3RhbF9yZWNlbnQgKiAxMDAgaWYgdG90YWxfcmVjZW50IGVsc2UgbnAu"
        "bmFuLAogICAgICAgICAgICAgICAgImV2b2x1dGlvbl92b2x1bWVfcGN0IjogZXZvX3ZvbHVtZSwKICAgICAgICAgICAgICAgICJw"
        "cml4X20yX21lZGlhbiI6IGJsb2NbInByaXhfbTIiXS5tZWRpYW4oKSwKICAgICAgICAgICAgICAgICJwcml4X21lZGlhbiI6IGJs"
        "b2NbInZhbGV1cl9mb25jaWVyZSJdLm1lZGlhbigpLAogICAgICAgICAgICAgICAgInN1cmZhY2VfbWVkaWFuZSI6IGJsb2NbInN1"
        "cmZhY2VfcmVlbGxlX2JhdGkiXS5tZWRpYW4oKSwKICAgICAgICAgICAgICAgICJldm9sdXRpb25fcHJpeF9tMl8zYW5zX3BjdCI6"
        "IF9ldm9sdXRpb25fcHJpeF9zZWdtZW50KHZlbnRlcywgc2VnbWVudCksCiAgICAgICAgICAgIH0KICAgICAgICApCgogICAgdGFi"
        "bGUgPSBwZC5EYXRhRnJhbWUobGlnbmVzKQogICAgaWYgdGFibGUuZW1wdHk6CiAgICAgICAgcmV0dXJuIHRhYmxlCgogICAgdGFi"
        "bGVbInJldGVudSJdID0gdGFibGVbInZlbnRlc19yZWNlbnRlcyJdID49IHNldWlsX3ZlbnRlcwogICAgZXZhbHVhYmxlcyA9IHRh"
        "YmxlW3RhYmxlWyJyZXRlbnUiXV0uY29weSgpCiAgICBpZiBldmFsdWFibGVzLmVtcHR5OgogICAgICAgIHRhYmxlWyJzY29yZV9k"
        "ZW1hbmRlIl0gPSBucC5uYW4KICAgICAgICByZXR1cm4gdGFibGUuc29ydF92YWx1ZXMoInZlbnRlc19yZWNlbnRlcyIsIGFzY2Vu"
        "ZGluZz1GYWxzZSkucmVzZXRfaW5kZXgoZHJvcD1UcnVlKQoKICAgIGNvbXBvc2FudGVzID0gcGQuRGF0YUZyYW1lKGluZGV4PWV2"
        "YWx1YWJsZXMuaW5kZXgpCiAgICBjb21wb3NhbnRlc1sicGFydF9tYXJjaGUiXSA9IF9yYW5nX25vcm1hbGlzZShldmFsdWFibGVz"
        "WyJwYXJ0X21hcmNoZV9wY3QiXSkKICAgIGNvbXBvc2FudGVzWyJldm9sdXRpb25fdm9sdW1lIl0gPSBfcmFuZ19ub3JtYWxpc2Uo"
        "ZXZhbHVhYmxlc1siZXZvbHV0aW9uX3ZvbHVtZV9wY3QiXSkKICAgIGNvbXBvc2FudGVzWyJldm9sdXRpb25fcHJpeCJdID0gX3Jh"
        "bmdfbm9ybWFsaXNlKGV2YWx1YWJsZXNbImV2b2x1dGlvbl9wcml4X20yXzNhbnNfcGN0Il0pCiAgICBjb21wb3NhbnRlc1sidm9s"
        "dW1lX2Fic29sdSJdID0gX3Jhbmdfbm9ybWFsaXNlKGV2YWx1YWJsZXNbInZlbnRlc19yZWNlbnRlcyJdKQoKICAgIHBvaWRzX3Rv"
        "dGFsID0gcGQuU2VyaWVzKDAuMCwgaW5kZXg9ZXZhbHVhYmxlcy5pbmRleCkKICAgIHNjb3JlID0gcGQuU2VyaWVzKDAuMCwgaW5k"
        "ZXg9ZXZhbHVhYmxlcy5pbmRleCkKICAgIGZvciBub20sIHBvaWRzIGluIFBPTkRFUkFUSU9OUy5pdGVtcygpOgogICAgICAgIHZh"
        "bGV1cnMgPSBjb21wb3NhbnRlc1tub21dCiAgICAgICAgcHJlc2VudGUgPSB2YWxldXJzLm5vdG5hKCkKICAgICAgICBzY29yZVtw"
        "cmVzZW50ZV0gKz0gdmFsZXVyc1twcmVzZW50ZV0gKiBwb2lkcwogICAgICAgIHBvaWRzX3RvdGFsW3ByZXNlbnRlXSArPSBwb2lk"
        "cwogICAgc2NvcmUgPSBucC53aGVyZShwb2lkc190b3RhbCA+IDAsIHNjb3JlIC8gcG9pZHNfdG90YWwgKiAxMDAsIG5wLm5hbikK"
        "CiAgICB0YWJsZVsic2NvcmVfZGVtYW5kZSJdID0gbnAubmFuCiAgICB0YWJsZS5sb2NbZXZhbHVhYmxlcy5pbmRleCwgInNjb3Jl"
        "X2RlbWFuZGUiXSA9IHNjb3JlCiAgICB0YWJsZSA9IHRhYmxlLnNvcnRfdmFsdWVzKAogICAgICAgIFsicmV0ZW51IiwgInNjb3Jl"
        "X2RlbWFuZGUiLCAidmVudGVzX3JlY2VudGVzIl0sIGFzY2VuZGluZz1bRmFsc2UsIEZhbHNlLCBGYWxzZV0KICAgICkucmVzZXRf"
        "aW5kZXgoZHJvcD1UcnVlKQogICAgcmV0dXJuIHRhYmxlCgoKZGVmIGNvbW1lbnRhaXJlKGxpZ25lOiBwZC5TZXJpZXMpIC0+IHN0"
        "cjoKICAgICIiIlBocmFzZSBkZSBsZWN0dXJlIHBvdXIgdW5lIHR5cG9sb2dpZS4iIiIKICAgIGJvdXRzID0gW2Yie2ludChsaWdu"
        "ZVsndmVudGVzX3JlY2VudGVzJ10pfSB2ZW50ZXMgc3VyIGxhIHBlcmlvZGUiXQogICAgaWYgcGQubm90bmEobGlnbmUuZ2V0KCJw"
        "YXJ0X21hcmNoZV9wY3QiKSk6CiAgICAgICAgYm91dHMuYXBwZW5kKGYie2xpZ25lWydwYXJ0X21hcmNoZV9wY3QnXTouMGZ9ICUg"
        "ZHUgbWFyY2hlIikKICAgIGlmIHBkLm5vdG5hKGxpZ25lLmdldCgiZXZvbHV0aW9uX3ZvbHVtZV9wY3QiKSk6CiAgICAgICAgc2Vu"
        "cyA9ICJoYXVzc2UiIGlmIGxpZ25lWyJldm9sdXRpb25fdm9sdW1lX3BjdCJdID49IDAgZWxzZSAiYmFpc3NlIgogICAgICAgIGJv"
        "dXRzLmFwcGVuZChmInZvbHVtZSBlbiB7c2Vuc30gZGUge2FicyhsaWduZVsnZXZvbHV0aW9uX3ZvbHVtZV9wY3QnXSk6LjBmfSAl"
        "IikKICAgIGlmIHBkLm5vdG5hKGxpZ25lLmdldCgiZXZvbHV0aW9uX3ByaXhfbTJfM2Fuc19wY3QiKSk6CiAgICAgICAgc2VucyA9"
        "ICIrIiBpZiBsaWduZVsiZXZvbHV0aW9uX3ByaXhfbTJfM2Fuc19wY3QiXSA+PSAwIGVsc2UgIiIKICAgICAgICBib3V0cy5hcHBl"
        "bmQoZiJwcml4L20yIHtzZW5zfXtsaWduZVsnZXZvbHV0aW9uX3ByaXhfbTJfM2Fuc19wY3QnXTouMGZ9ICUgc3VyIDMgYW5zIikK"
        "ICAgIHJldHVybiAiLCAiLmpvaW4oYm91dHMpCgoKZGVmIHN5bnRoZXNlKHRhYmxlOiBwZC5EYXRhRnJhbWUsIG5vbWJyZTogaW50"
        "ID0gMykgLT4gZGljdDoKICAgICIiIlR5cG9sb2dpZXMgbGVzIHBsdXMgZXQgbGVzIG1vaW5zIGRlbWFuZGVlcy4iIiIKICAgIGlm"
        "IHRhYmxlLmVtcHR5IG9yICJzY29yZV9kZW1hbmRlIiBub3QgaW4gdGFibGU6CiAgICAgICAgcmV0dXJuIHsicGx1c19kZW1hbmRl"
        "cyI6IHBkLkRhdGFGcmFtZSgpLCAibW9pbnNfZGVtYW5kZXMiOiBwZC5EYXRhRnJhbWUoKX0KICAgIGV2YWx1YWJsZXMgPSB0YWJs"
        "ZVt0YWJsZVsicmV0ZW51Il0gJiB0YWJsZVsic2NvcmVfZGVtYW5kZSJdLm5vdG5hKCldCiAgICByZXR1cm4gewogICAgICAgICJw"
        "bHVzX2RlbWFuZGVzIjogZXZhbHVhYmxlcy5oZWFkKG5vbWJyZSksCiAgICAgICAgIm1vaW5zX2RlbWFuZGVzIjogZXZhbHVhYmxl"
        "cy50YWlsKG5vbWJyZSkuaWxvY1s6Oi0xXSwKICAgICAgICAiaG9yc19hbmFseXNlIjogdGFibGVbfnRhYmxlWyJyZXRlbnUiXV0s"
        "CiAgICB9Cg=="
    ),
    "actualite": (
        "IiIiVmVpbGxlIGxvY2FsZSA6IGFjdHVhbGl0ZXMgZGUgbGEgY29tbXVuZSBldCBlcXVpcGVtZW50cyBzdHJ1Y3R1cmFudHMuIiIi"
        "CmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmltcG9ydCBkYXRldGltZSBhcyBkdAppbXBvcnQgZW1haWwudXRp"
        "bHMgYXMgZXV0CmltcG9ydCB4bWwuZXRyZWUuRWxlbWVudFRyZWUgYXMgRVQKCmZyb20gLmNvbmZpZyBpbXBvcnQgTkVXU19SU1MK"
        "ZnJvbSAuaHR0cCBpbXBvcnQgU291cmNlRXJyb3IsIGdldCwgZ2V0X2pzb24KClRIRU1FUyA9IHsKICAgICJVcmJhbmlzbWUgZXQg"
        "dHJhdmF1eCI6ICJ1cmJhbmlzbWUgT1IgY2hhbnRpZXIgT1IgdHJhdmF1eCBPUiBcInBlcm1pcyBkZSBjb25zdHJ1aXJlXCIgT1Ig"
        "WkFDIE9SIHJlbm92YXRpb24iLAogICAgIkVjb25vbWllIGV0IGVtcGxvaSI6ICJ1c2luZSBPUiBlbnRyZXByaXNlIE9SIGVtcGxv"
        "aXMgT1IgaW1wbGFudGF0aW9uIE9SIHpvbmUgZCdhY3Rpdml0ZSBPUiBmZXJtZXR1cmUiLAogICAgIkVxdWlwZW1lbnRzIGV0IGVj"
        "b2xlcyI6ICJlY29sZSBPUiBjb2xsZWdlIE9SIGx5Y2VlIE9SIGNyZWNoZSBPUiBob3BpdGFsIE9SIGdhcmUgT1IgdHJhbXdheSBP"
        "UiBlcXVpcGVtZW50IiwKICAgICJJbW1vYmlsaWVyIGV0IGxvZ2VtZW50IjogImltbW9iaWxpZXIgT1IgbG9nZW1lbnRzIE9SIHBy"
        "b2dyYW1tZSBpbW1vYmlsaWVyIE9SIG1hcmNoZSBpbW1vYmlsaWVyIE9SIGxveWVycyIsCiAgICAiVmllIGxvY2FsZSI6ICJtYWly"
        "aWUgT1IgY29uc2VpbCBtdW5pY2lwYWwgT1IgcXVhcnRpZXIgT1IgY29tbWVyY2VzIiwKfQoKQVBJX0VDT0xFUyA9ICJodHRwczov"
        "L2RhdGEuZWR1Y2F0aW9uLmdvdXYuZnIvYXBpL2V4cGxvcmUvdjIuMS9jYXRhbG9nL2RhdGFzZXRzL2ZyLWVuLWFubnVhaXJlLWVk"
        "dWNhdGlvbi9yZWNvcmRzIgoKCmRlZiBfcmVxdWV0ZV9yc3MocmVxdWV0ZTogc3RyLCBhbmNpZW5uZXRlX21vaXM6IGludCA9IDI0"
        "LCBsaW1pdGU6IGludCA9IDgpIC0+IGxpc3RbZGljdF06CiAgICBwYXJhbXMgPSB7CiAgICAgICAgInEiOiBmIntyZXF1ZXRlfSB3"
        "aGVuOnthbmNpZW5uZXRlX21vaXN9bSIsCiAgICAgICAgImhsIjogImZyIiwKICAgICAgICAiZ2wiOiAiRlIiLAogICAgICAgICJj"
        "ZWlkIjogIkZSOmZyIiwKICAgIH0KICAgIHJlcG9uc2UgPSBnZXQoTkVXU19SU1MsIHBhcmFtcz1wYXJhbXMsIHRpbWVvdXQ9MzAp"
        "CiAgICBpZiByZXBvbnNlLnN0YXR1c19jb2RlICE9IDIwMDoKICAgICAgICByYWlzZSBTb3VyY2VFcnJvcihmIkZsdXggYWN0dWFs"
        "aXRlcyA6IHJlcG9uc2Uge3JlcG9uc2Uuc3RhdHVzX2NvZGV9IikKICAgIHRyeToKICAgICAgICByYWNpbmUgPSBFVC5mcm9tc3Ry"
        "aW5nKHJlcG9uc2UuY29udGVudCkKICAgIGV4Y2VwdCBFVC5QYXJzZUVycm9yIGFzIGV4YzoKICAgICAgICByYWlzZSBTb3VyY2VF"
        "cnJvcigiRmx1eCBhY3R1YWxpdGVzIGlsbGlzaWJsZSIpIGZyb20gZXhjCgogICAgYXJ0aWNsZXMgPSBbXQogICAgZm9yIGl0ZW0g"
        "aW4gcmFjaW5lLml0ZXIoIml0ZW0iKToKICAgICAgICB0aXRyZSA9IChpdGVtLmZpbmR0ZXh0KCJ0aXRsZSIpIG9yICIiKS5zdHJp"
        "cCgpCiAgICAgICAgbGllbiA9IChpdGVtLmZpbmR0ZXh0KCJsaW5rIikgb3IgIiIpLnN0cmlwKCkKICAgICAgICBzb3VyY2UgPSBp"
        "dGVtLmZpbmR0ZXh0KCJzb3VyY2UiKSBvciAiIgogICAgICAgIHB1YmxpZSA9IGl0ZW0uZmluZHRleHQoInB1YkRhdGUiKQogICAg"
        "ICAgIGRhdGUgPSBOb25lCiAgICAgICAgaWYgcHVibGllOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBkYXRlID0g"
        "ZXV0LnBhcnNlZGF0ZV90b19kYXRldGltZShwdWJsaWUpLmRhdGUoKQogICAgICAgICAgICBleGNlcHQgKFR5cGVFcnJvciwgVmFs"
        "dWVFcnJvcik6CiAgICAgICAgICAgICAgICBkYXRlID0gTm9uZQogICAgICAgICMgR29vZ2xlIE5ld3Mgc3VmZml4ZSBsZSB0aXRy"
        "ZSBwYXIgIiAtIFNvdXJjZSIKICAgICAgICBpZiBzb3VyY2UgYW5kIHRpdHJlLmVuZHN3aXRoKGYiIC0ge3NvdXJjZX0iKToKICAg"
        "ICAgICAgICAgdGl0cmUgPSB0aXRyZVs6IC0obGVuKHNvdXJjZSkgKyAzKV0KICAgICAgICBhcnRpY2xlcy5hcHBlbmQoeyJ0aXRy"
        "ZSI6IHRpdHJlLCAibGllbiI6IGxpZW4sICJzb3VyY2UiOiBzb3VyY2Uuc3RyaXAoKSwgImRhdGUiOiBkYXRlfSkKICAgICAgICBp"
        "ZiBsZW4oYXJ0aWNsZXMpID49IGxpbWl0ZToKICAgICAgICAgICAgYnJlYWsKICAgIHJldHVybiBhcnRpY2xlcwoKCmRlZiBhY3R1"
        "YWxpdGVzKG5vbV9jb21tdW5lOiBzdHIsIGRlcGFydGVtZW50OiBzdHIgfCBOb25lID0gTm9uZSwgYW5jaWVubmV0ZV9tb2lzOiBp"
        "bnQgPSAyNCkgLT4gZGljdDoKICAgICIiIkFjdHVhbGl0ZXMgbG9jYWxlcyBjbGFzc2VlcyBwYXIgdGhlbWUuIiIiCiAgICBiYXNl"
        "ID0gZicie25vbV9jb21tdW5lfSInCiAgICBpZiBkZXBhcnRlbWVudDoKICAgICAgICBiYXNlID0gZid7YmFzZX0ge2RlcGFydGVt"
        "ZW50fScKICAgIHJlc3VsdGF0OiBkaWN0W3N0ciwgbGlzdFtkaWN0XV0gPSB7fQogICAgZXJyZXVycyA9IFtdCiAgICB2dXMgPSBz"
        "ZXQoKQogICAgZm9yIHRoZW1lLCBtb3RzIGluIFRIRU1FUy5pdGVtcygpOgogICAgICAgIHRyeToKICAgICAgICAgICAgYXJ0aWNs"
        "ZXMgPSBfcmVxdWV0ZV9yc3MoZiJ7YmFzZX0gKHttb3RzfSkiLCBhbmNpZW5uZXRlX21vaXM9YW5jaWVubmV0ZV9tb2lzKQogICAg"
        "ICAgIGV4Y2VwdCBTb3VyY2VFcnJvciBhcyBleGM6CiAgICAgICAgICAgIGVycmV1cnMuYXBwZW5kKGYie3RoZW1lfSA6IHtleGN9"
        "IikKICAgICAgICAgICAgY29udGludWUKICAgICAgICByZXRlbnVzID0gW10KICAgICAgICBmb3IgYXJ0aWNsZSBpbiBhcnRpY2xl"
        "czoKICAgICAgICAgICAgY2xlID0gYXJ0aWNsZVsidGl0cmUiXS5sb3dlcigpWzo4MF0KICAgICAgICAgICAgaWYgY2xlIGluIHZ1"
        "cyBvciBub3QgYXJ0aWNsZVsidGl0cmUiXToKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHZ1cy5hZGQoY2xl"
        "KQogICAgICAgICAgICByZXRlbnVzLmFwcGVuZChhcnRpY2xlKQogICAgICAgIGlmIHJldGVudXM6CiAgICAgICAgICAgIHJlc3Vs"
        "dGF0W3RoZW1lXSA9IHJldGVudXMKICAgIHJldHVybiB7InRoZW1lcyI6IHJlc3VsdGF0LCAiZXJyZXVycyI6IGVycmV1cnN9CgoK"
        "ZGVmIGVxdWlwZW1lbnRzX3Njb2xhaXJlcyhjb2RlX2luc2VlOiBzdHIpIC0+IGRpY3Q6CiAgICAiIiJFdGFibGlzc2VtZW50cyBz"
        "Y29sYWlyZXMgcmVjZW5zZXMgZGFucyBsJ2FubnVhaXJlIGRlIGwnZWR1Y2F0aW9uIG5hdGlvbmFsZS4iIiIKICAgIHBhcmFtcyA9"
        "IHsKICAgICAgICAid2hlcmUiOiBmJ2NvZGVfY29tbXVuZT0ie2NvZGVfaW5zZWV9IicsCiAgICAgICAgImxpbWl0IjogMTAwLAog"
        "ICAgICAgICJzZWxlY3QiOiAibm9tX2V0YWJsaXNzZW1lbnQsdHlwZV9ldGFibGlzc2VtZW50LHN0YXR1dF9wdWJsaWNfcHJpdmUs"
        "ZGF0ZV9vdXZlcnR1cmUsbGliZWxsZV9uYXR1cmUiLAogICAgfQogICAgZG9ubmVlcyA9IGdldF9qc29uKEFQSV9FQ09MRVMsIHBh"
        "cmFtcz1wYXJhbXMpCiAgICBsaWduZXMgPSBkb25uZWVzLmdldCgicmVzdWx0cyIsIFtdKQogICAgcmVjZW50cyA9IFtdCiAgICBz"
        "ZXVpbCA9IGR0LmRhdGUudG9kYXkoKSAtIGR0LnRpbWVkZWx0YShkYXlzPTM2NSAqIDUpCiAgICBmb3IgbGlnbmUgaW4gbGlnbmVz"
        "OgogICAgICAgIG91dmVydHVyZSA9IGxpZ25lLmdldCgiZGF0ZV9vdXZlcnR1cmUiKQogICAgICAgIGlmIG5vdCBvdXZlcnR1cmU6"
        "CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgdHJ5OgogICAgICAgICAgICBkYXRlID0gZHQuZGF0ZS5mcm9taXNvZm9ybWF0"
        "KHN0cihvdXZlcnR1cmUpWzoxMF0pCiAgICAgICAgZXhjZXB0IFZhbHVlRXJyb3I6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAg"
        "ICAgaWYgZGF0ZSA+PSBzZXVpbDoKICAgICAgICAgICAgcmVjZW50cy5hcHBlbmQoeyoqbGlnbmUsICJkYXRlX291dmVydHVyZSI6"
        "IGRhdGUuaXNvZm9ybWF0KCl9KQogICAgcmVwYXJ0aXRpb246IGRpY3Rbc3RyLCBpbnRdID0ge30KICAgIGZvciBsaWduZSBpbiBs"
        "aWduZXM6CiAgICAgICAgY2xlID0gbGlnbmUuZ2V0KCJ0eXBlX2V0YWJsaXNzZW1lbnQiKSBvciAiQXV0cmUiCiAgICAgICAgcmVw"
        "YXJ0aXRpb25bY2xlXSA9IHJlcGFydGl0aW9uLmdldChjbGUsIDApICsgMQogICAgcmV0dXJuIHsidG90YWwiOiBsZW4obGlnbmVz"
        "KSwgInJlcGFydGl0aW9uIjogcmVwYXJ0aXRpb24sICJvdXZlcnR1cmVzX3JlY2VudGVzIjogcmVjZW50c30K"
    ),
    "export": (
        "IiIiRXhwb3J0IGR1IGRvc3NpZXIgZGUgdmlsbGUgYXUgZm9ybWF0IEV4Y2VsLiIiIgpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFu"
        "bm90YXRpb25zCgppbXBvcnQgaW8KCmltcG9ydCBwYW5kYXMgYXMgcGQKCgpkZWYgY2xhc3NldXIoY29tbXVuZTogZGljdCwgcG9w"
        "dWxhdGlvbjogZGljdCwgdGFibGVfcHJpeDogcGQuRGF0YUZyYW1lLCB0YWJsZV9kZW1hbmRlOiBwZC5EYXRhRnJhbWUsCiAgICAg"
        "ICAgICAgICB2ZW50ZXM6IHBkLkRhdGFGcmFtZSwgYWN0dXM6IGRpY3QpIC0+IGJ5dGVzOgogICAgdGFtcG9uID0gaW8uQnl0ZXNJ"
        "TygpCiAgICB3aXRoIHBkLkV4Y2VsV3JpdGVyKHRhbXBvbiwgZW5naW5lPSJvcGVucHl4bCIpIGFzIHdyaXRlcjoKICAgICAgICBz"
        "eW50aGVzZSA9IFsKICAgICAgICAgICAgKCJDb21tdW5lIiwgY29tbXVuZS5nZXQoIm5vbSIpKSwKICAgICAgICAgICAgKCJDb2Rl"
        "IEluc2VlIiwgY29tbXVuZS5nZXQoImNvZGUiKSksCiAgICAgICAgICAgICgiRMOpcGFydGVtZW50IiwgY29tbXVuZS5nZXQoImNv"
        "ZGVEZXBhcnRlbWVudCIpKSwKICAgICAgICAgICAgKCJQb3B1bGF0aW9uIChkZXJuaWVyIG1pbGzDqXNpbWUpIiwgcG9wdWxhdGlv"
        "bi5nZXQoInBvcHVsYXRpb25fYWN0dWVsbGUiKSksCiAgICAgICAgXQogICAgICAgIGZvciBjbGUsIGxpYmVsbGUgaW4gKCgiY291"
        "cnRfdGVybWUiLCAiw4l2b2x1dGlvbiBwb3B1bGF0aW9uIDIgYW5zIiksICgibW95ZW5fdGVybWUiLCAiw4l2b2x1dGlvbiBwb3B1"
        "bGF0aW9uIDUgYW5zIikpOgogICAgICAgICAgICBibG9jID0gcG9wdWxhdGlvbi5nZXQoY2xlKQogICAgICAgICAgICBpZiBibG9j"
        "OgogICAgICAgICAgICAgICAgc3ludGhlc2UuYXBwZW5kKAogICAgICAgICAgICAgICAgICAgIChmIntsaWJlbGxlfSAoe2Jsb2Nb"
        "J2FubmVlX2RlYnV0J1194oaSe2Jsb2NbJ2FubmVlX2ZpbiddfSkiLCBmIntibG9jWyd2YXJpYXRpb25fcGN0J106LjJmfSAlIikK"
        "ICAgICAgICAgICAgICAgICkKICAgICAgICBpZiBub3QgdGFibGVfcHJpeC5lbXB0eToKICAgICAgICAgICAgZGVybmllcmUgPSB0"
        "YWJsZV9wcml4Lmlsb2NbLTFdCiAgICAgICAgICAgIHN5bnRoZXNlLmFwcGVuZCgoZiJQcml4IG3DqWRpYW4gYXUgbcKyICh7aW50"
        "KGRlcm5pZXJlWydhbm5lZSddKX0pIiwgcm91bmQoZmxvYXQoZGVybmllcmVbInByaXhfbTJfbWVkaWFuIl0pLCAwKSkpCiAgICAg"
        "ICAgICAgIHN5bnRoZXNlLmFwcGVuZCgoZiJWZW50ZXMgYW5hbHlzw6llcyAoe2ludChkZXJuaWVyZVsnYW5uZWUnXSl9KSIsIGlu"
        "dChkZXJuaWVyZVsidmVudGVzIl0pKSkKICAgICAgICBwZC5EYXRhRnJhbWUoc3ludGhlc2UsIGNvbHVtbnM9WyJJbmRpY2F0ZXVy"
        "IiwgIlZhbGV1ciJdKS50b19leGNlbCh3cml0ZXIsIHNoZWV0X25hbWU9IlN5bnRow6hzZSIsIGluZGV4PUZhbHNlKQoKICAgICAg"
        "ICBpZiBwb3B1bGF0aW9uLmdldCgic2VyaWUiKToKICAgICAgICAgICAgcGQuRGF0YUZyYW1lKAogICAgICAgICAgICAgICAgc29y"
        "dGVkKHBvcHVsYXRpb25bInNlcmllIl0uaXRlbXMoKSksIGNvbHVtbnM9WyJBbm7DqWUiLCAiUG9wdWxhdGlvbiBtdW5pY2lwYWxl"
        "Il0KICAgICAgICAgICAgKS50b19leGNlbCh3cml0ZXIsIHNoZWV0X25hbWU9IlBvcHVsYXRpb24iLCBpbmRleD1GYWxzZSkKCiAg"
        "ICAgICAgaWYgbm90IHRhYmxlX3ByaXguZW1wdHk6CiAgICAgICAgICAgIHRhYmxlX3ByaXgudG9fZXhjZWwod3JpdGVyLCBzaGVl"
        "dF9uYW1lPSJQcml4IHBhciBhbm7DqWUiLCBpbmRleD1GYWxzZSkKICAgICAgICBpZiBub3QgdGFibGVfZGVtYW5kZS5lbXB0eToK"
        "ICAgICAgICAgICAgdGFibGVfZGVtYW5kZS50b19leGNlbCh3cml0ZXIsIHNoZWV0X25hbWU9IlR5cG9sb2dpZXMiLCBpbmRleD1G"
        "YWxzZSkKICAgICAgICBpZiB2ZW50ZXMgaXMgbm90IE5vbmUgYW5kIG5vdCB2ZW50ZXMuZW1wdHk6CiAgICAgICAgICAgIGNvbG9u"
        "bmVzID0gWwogICAgICAgICAgICAgICAgYwogICAgICAgICAgICAgICAgZm9yIGMgaW4gWwogICAgICAgICAgICAgICAgICAgICJk"
        "YXRlX211dGF0aW9uIiwgInR5cGVfbG9jYWwiLCAicGllY2VzIiwgInN1cmZhY2VfcmVlbGxlX2JhdGkiLAogICAgICAgICAgICAg"
        "ICAgICAgICJ2YWxldXJfZm9uY2llcmUiLCAicHJpeF9tMiIsICJ0ZXJyYWluX3RvdGFsIiwgIm5iX2RlcGVuZGFuY2VzIiwKICAg"
        "ICAgICAgICAgICAgICAgICAiYWRyZXNzZV9ub21fdm9pZSIsICJjb2RlX3Bvc3RhbCIsCiAgICAgICAgICAgICAgICBdCiAgICAg"
        "ICAgICAgICAgICBpZiBjIGluIHZlbnRlcy5jb2x1bW5zCiAgICAgICAgICAgIF0KICAgICAgICAgICAgdmVudGVzLnNvcnRfdmFs"
        "dWVzKCJkYXRlX211dGF0aW9uIiwgYXNjZW5kaW5nPUZhbHNlKVtjb2xvbm5lc10udG9fZXhjZWwoCiAgICAgICAgICAgICAgICB3"
        "cml0ZXIsIHNoZWV0X25hbWU9IlZlbnRlcyBkw6l0YWlsbMOpZXMiLCBpbmRleD1GYWxzZQogICAgICAgICAgICApCiAgICAgICAg"
        "bGlnbmVzX2FjdHUgPSBbXQogICAgICAgIGZvciB0aGVtZSwgYXJ0aWNsZXMgaW4gKGFjdHVzLmdldCgidGhlbWVzIikgb3Ige30p"
        "Lml0ZW1zKCk6CiAgICAgICAgICAgIGZvciBhcnRpY2xlIGluIGFydGljbGVzOgogICAgICAgICAgICAgICAgbGlnbmVzX2FjdHUu"
        "YXBwZW5kKAogICAgICAgICAgICAgICAgICAgIHsiVGjDqG1lIjogdGhlbWUsICJEYXRlIjogYXJ0aWNsZS5nZXQoImRhdGUiKSwg"
        "IlRpdHJlIjogYXJ0aWNsZS5nZXQoInRpdHJlIiksCiAgICAgICAgICAgICAgICAgICAgICJTb3VyY2UiOiBhcnRpY2xlLmdldCgi"
        "c291cmNlIiksICJMaWVuIjogYXJ0aWNsZS5nZXQoImxpZW4iKX0KICAgICAgICAgICAgICAgICkKICAgICAgICBpZiBsaWduZXNf"
        "YWN0dToKICAgICAgICAgICAgcGQuRGF0YUZyYW1lKGxpZ25lc19hY3R1KS50b19leGNlbCh3cml0ZXIsIHNoZWV0X25hbWU9IkFj"
        "dHVhbGl0w6lzIiwgaW5kZXg9RmFsc2UpCiAgICByZXR1cm4gdGFtcG9uLmdldHZhbHVlKCkK"
    ),
}

# Streamlit réexécute ce script à chaque interaction : on ne reconstruit le paquet
# qu'une seule fois par processus.
if "immo" not in _sys.modules:
    _PAQUET = _types.ModuleType("immo")
    _PAQUET.__path__ = []
    _sys.modules["immo"] = _PAQUET
    for _nom, _source in _SOURCES.items():
        _module = _types.ModuleType("immo." + _nom)
        _module.__package__ = "immo"
        _sys.modules["immo." + _nom] = _module
        setattr(_PAQUET, _nom, _module)
        exec(
            compile(_b64.b64decode(_source).decode("utf-8"), "immo/" + _nom + ".py", "exec"),
            _module.__dict__,
        )

# --------------------------------------------------------------------------- #
# Application
# --------------------------------------------------------------------------- #
"""Analyse Immo — étude de marché communale pour l'achat-revente.

Lancement : streamlit run app.py
"""

import datetime as dt

import pandas as pd
import streamlit as st

from immo import actualite, demande, dvf, export, geo, population
from immo.config import CACHE_DIR
from immo.http import SourceError

st.set_page_config(page_title="Analyse Immo — étude de ville", page_icon="🏘️", layout="wide")


# --------------------------------------------------------------------------- #
# Chargements mis en cache
# --------------------------------------------------------------------------- #
@st.cache_data(show_spinner=False, ttl=3600)
def _chercher(saisie: str):
    return geo.chercher(saisie)


@st.cache_data(show_spinner=False, ttl=24 * 3600)
def _population(code_insee: str, secours: int | None):
    return population.analyse(code_insee, secours)


@st.cache_data(show_spinner=False, ttl=24 * 3600)
def _ventes(code_insee: str, profondeur: int):
    annees = dvf.annees_disponibles(code_insee, profondeur=profondeur)
    brut = dvf.charger(code_insee, annees)
    return dvf.preparer(brut), annees


@st.cache_data(show_spinner=False, ttl=6 * 3600)
def _actualites(nom: str, departement: str, mois: int):
    return actualite.actualites(nom, departement, anciennete_mois=mois)


@st.cache_data(show_spinner=False, ttl=24 * 3600)
def _ecoles(code_insee: str):
    return actualite.equipements_scolaires(code_insee)


def _pourcent(valeur, decimales: int = 1) -> str:
    if valeur is None or pd.isna(valeur):
        return "n.d."
    return f"{valeur:+.{decimales}f} %"


def _euros(valeur, decimales: int = 0) -> str:
    if valeur is None or pd.isna(valeur):
        return "n.d."
    return f"{valeur:,.{decimales}f} €".replace(",", " ")


# --------------------------------------------------------------------------- #
# Barre latérale : choix de la commune
# --------------------------------------------------------------------------- #
st.sidebar.title("🏘️ Analyse Immo")
saisie = st.sidebar.text_input("Ville ou code postal", placeholder="Ex. Tourcoing ou 59200")

profondeur = st.sidebar.slider("Profondeur des données de ventes (années)", 3, 8, 6)
fenetre = st.sidebar.select_slider(
    "Période de référence pour la demande", options=[12, 18, 24, 36], value=24,
    format_func=lambda m: f"{m} mois",
)
seuil = st.sidebar.number_input("Ventes minimum pour classer une typologie", 3, 30, 5)

with st.sidebar.expander("Maintenance"):
    st.caption(f"Cache local : {CACHE_DIR}")
    if st.button("Vider le cache et recharger"):
        st.cache_data.clear()
        for fichier in CACHE_DIR.rglob("*"):
            if fichier.is_file():
                fichier.unlink()
        st.success("Cache vidé.")

commune = None
if saisie:
    try:
        resultats = _chercher(saisie)
    except SourceError as exc:
        st.sidebar.error(f"Recherche impossible : {exc}")
        resultats = []
    if not resultats:
        st.sidebar.warning("Aucune commune trouvée.")
    elif len(resultats) == 1:
        commune = resultats[0]
    else:
        choix = st.sidebar.selectbox(
            "Commune", options=list(range(len(resultats))), format_func=lambda i: geo.libelle(resultats[i])
        )
        commune = resultats[choix]

if commune is None:
    st.title("Étude de marché communale")
    st.markdown(
        """
Saisissez une ville dans le panneau de gauche. L'outil assemble, pour la commune choisie :

- l'**évolution de la population** sur 2 et 5 ans (populations légales Insee) ;
- le **prix moyen et médian au m²** et son **évolution sur 3 ans** (ventes DVF de la DGFiP) ;
- les **typologies de biens les plus et les moins demandées**, estimées à partir des ventes réellement
  conclues : volumes, parts de marché, dynamique des volumes et des prix ;
- une **veille d'actualité locale** (urbanisme, économie, équipements, logement) pour apprécier l'offre
  à venir et les projets structurants.

Toutes les données sont publiques et gratuites. Les premiers chargements sont plus longs :
les fichiers sont ensuite conservés en cache local.
        """
    )
    st.stop()


# --------------------------------------------------------------------------- #
# Chargement des données de la commune
# --------------------------------------------------------------------------- #
nom = commune["nom"]
code = commune["code"]
st.title(f"{nom} ({commune.get('codeDepartement')})")

with st.spinner("Population Insee…"):
    pop = _population(code, commune.get("population"))

ventes, annees = pd.DataFrame(), []
erreur_dvf = None
with st.spinner("Ventes DVF — premier chargement long…"):
    try:
        ventes, annees = _ventes(code, profondeur)
    except SourceError as exc:
        erreur_dvf = str(exc)

table_prix = dvf.prix_par_annee(ventes) if not ventes.empty else pd.DataFrame()
evolution_3ans = dvf.evolution_prix(table_prix, recul=3) if not table_prix.empty else None
table_demande = demande.analyser(ventes, mois=fenetre, seuil_ventes=int(seuil)) if not ventes.empty else pd.DataFrame()
vue_demande = demande.synthese(table_demande) if not table_demande.empty else {}

# Indicateurs de tête
c1, c2, c3, c4 = st.columns(4)
c1.metric(
    "Population",
    f"{pop.get('population_actuelle', 0):,}".replace(",", " ") if pop.get("population_actuelle") else "n.d.",
    help="Population municipale, dernier millésime Insee disponible.",
)
court = pop.get("court_terme")
moyen = pop.get("moyen_terme")


def _periode(bloc) -> str:
    return " ({}→{})".format(bloc["annee_debut"], bloc["annee_fin"]) if bloc else ""


c2.metric(
    "Population 2 ans" + _periode(court),
    _pourcent(court["variation_pct"]) if court else "n.d.",
)
c3.metric(
    "Population 5 ans" + _periode(moyen),
    _pourcent(moyen["variation_pct"]) if moyen else "n.d.",
)
if not table_prix.empty:
    derniere = table_prix.iloc[-1]
    c4.metric(
        f"Prix médian au m² ({int(derniere['annee'])})",
        _euros(derniere["prix_m2_median"]),
        _pourcent(evolution_3ans["variation_pct"]) if evolution_3ans else None,
        help="Variation affichée : évolution sur 3 ans du prix médian au m².",
    )
else:
    c4.metric("Prix médian au m²", "n.d.")

if erreur_dvf:
    st.error(f"Données de ventes indisponibles : {erreur_dvf}")

onglets = st.tabs(
    ["Synthèse", "Population", "Prix au m²", "Typologies", "Actualité locale", "Méthode et sources"]
)


# --------------------------------------------------------------------------- #
# Synthèse
# --------------------------------------------------------------------------- #
with onglets[0]:
    gauche, droite = st.columns(2)

    with gauche:
        st.subheader("Démographie")
        if pop.get("serie"):
            serie = pd.Series(pop["serie"]).sort_index()
            st.line_chart(serie.rename("Population municipale"))
            if court and moyen:
                st.caption(
                    f"{court['population_debut']:,} hab. en {court['annee_debut']} → "
                    f"{court['population_fin']:,} hab. en {court['annee_fin']} "
                    f"({_pourcent(court['variation_pct'])}, soit {_pourcent(court['tcam_pct'])}/an). "
                    f"Sur 5 ans : {_pourcent(moyen['variation_pct'])}.".replace(",", " ")
                )
        else:
            st.info(pop.get("message") or "Série de population indisponible.")

    with droite:
        st.subheader("Marché")
        if not table_prix.empty:
            graphe = table_prix.set_index("annee")[["prix_m2_median"]].rename(
                columns={"prix_m2_median": "Prix médian au m²"}
            )
            st.line_chart(graphe)
            if evolution_3ans:
                st.caption(
                    f"{_euros(evolution_3ans['valeur_debut'])}/m² en {evolution_3ans['annee_debut']} → "
                    f"{_euros(evolution_3ans['valeur_fin'])}/m² en {evolution_3ans['annee_fin']} "
                    f"({_pourcent(evolution_3ans['variation_pct'])}, soit {_pourcent(evolution_3ans['tcam_pct'])}/an)."
                )
        else:
            st.info("Pas de ventes exploitables sur la période.")

    if vue_demande:
        st.subheader("Typologies les plus et les moins demandées")
        col_plus, col_moins = st.columns(2)
        with col_plus:
            st.markdown("**Les plus demandées**")
            for _, ligne in vue_demande["plus_demandes"].iterrows():
                st.markdown(
                    f"- **{ligne['segment']}** — score {ligne['score_demande']:.0f}/100 · "
                    f"{demande.commentaire(ligne)} · prix médian {_euros(ligne['prix_m2_median'])}/m²"
                )
        with col_moins:
            st.markdown("**Les moins demandées**")
            for _, ligne in vue_demande["moins_demandes"].iterrows():
                st.markdown(
                    f"- **{ligne['segment']}** — score {ligne['score_demande']:.0f}/100 · "
                    f"{demande.commentaire(ligne)} · prix médian {_euros(ligne['prix_m2_median'])}/m²"
                )
        st.caption(
            "Score relatif à la commune, calculé sur les ventes conclues "
            f"des {fenetre} derniers mois couverts par DVF. Il n'existe pas de statistique publique "
            "de la demande : ce classement est un indicateur de rotation et de tension, pas une mesure directe."
        )

    couverture = dvf.couverture(ventes)
    if couverture:
        st.caption(
            f"{couverture['ventes']} ventes de logements exploitées, du {couverture['debut']:%d/%m/%Y} "
            f"au {couverture['fin']:%d/%m/%Y} (années {min(annees)}–{max(annees)})."
        )

    # Export
    if not ventes.empty:
        try:
            actus_export = _actualites(nom, commune.get("codeDepartement"), 24)
        except SourceError:
            actus_export = {"themes": {}}
        fichier = export.classeur(commune, pop, table_prix, table_demande, ventes, actus_export)
        st.download_button(
            "📥 Télécharger le dossier Excel",
            data=fichier,
            file_name=f"analyse_{nom.lower().replace(' ', '_')}_{dt.date.today():%Y%m%d}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )


# --------------------------------------------------------------------------- #
# Population
# --------------------------------------------------------------------------- #
with onglets[1]:
    if pop.get("serie"):
        serie = pd.Series(pop["serie"]).sort_index()
        tableau = pd.DataFrame({"Année": serie.index, "Population municipale": serie.values})
        tableau["Variation annuelle"] = serie.diff().values
        tableau["Variation (%)"] = (serie.pct_change() * 100).round(2).values
        st.dataframe(tableau, hide_index=True, width="stretch")
        st.bar_chart(serie.diff().dropna().rename("Variation entre millésimes"))
        for cle, libelle in (("court_terme", "Sur 2 ans"), ("moyen_terme", "Sur 5 ans")):
            bloc = pop.get(cle)
            if bloc:
                st.markdown(
                    f"**{libelle} ({bloc['annee_debut']} → {bloc['annee_fin']})** : "
                    f"{bloc['variation']:+,} habitants, {_pourcent(bloc['variation_pct'])} "
                    f"({_pourcent(bloc['tcam_pct'])} par an)".replace(",", " ")
                )
        st.caption(
            "Les populations légales sont publiées avec trois ans de décalage : le millésime le plus "
            "récent décrit la population de l'année de référence, pas celle d'aujourd'hui."
        )
    else:
        st.info(pop.get("message") or "Série de population indisponible.")
        if commune.get("population"):
            st.metric("Population (API Découpage administratif)", f"{commune['population']:,}".replace(",", " "))


# --------------------------------------------------------------------------- #
# Prix au m²
# --------------------------------------------------------------------------- #
with onglets[2]:
    if table_prix.empty:
        st.info("Pas de données de prix exploitables.")
    else:
        affichage = table_prix.rename(
            columns={
                "annee": "Année",
                "ventes": "Ventes",
                "prix_m2_median": "Prix médian €/m²",
                "prix_m2_moyen": "Prix moyen €/m²",
                "prix_median": "Prix médian du bien",
                "surface_mediane": "Surface médiane (m²)",
                "ventes_appartement": "Ventes appartements",
                "prix_m2_median_appartement": "€/m² médian appartement",
                "ventes_maison": "Ventes maisons",
                "prix_m2_median_maison": "€/m² médian maison",
            }
        )
        st.dataframe(affichage.round(0), hide_index=True, width="stretch")

        comparaison = table_prix.set_index("annee")[
            ["prix_m2_median_appartement", "prix_m2_median_maison"]
        ].rename(columns={"prix_m2_median_appartement": "Appartement", "prix_m2_median_maison": "Maison"})
        st.line_chart(comparaison)

        for type_local, colonne in (("Appartements", "prix_m2_median_appartement"), ("Maisons", "prix_m2_median_maison")):
            evo = dvf.evolution_prix(table_prix, recul=3, colonne=colonne)
            if evo:
                st.markdown(
                    f"**{type_local}** : {_euros(evo['valeur_debut'])}/m² en {evo['annee_debut']} → "
                    f"{_euros(evo['valeur_fin'])}/m² en {evo['annee_fin']} "
                    f"({_pourcent(evo['variation_pct'])}, {_pourcent(evo['tcam_pct'])} par an)."
                )

        st.caption(
            "Prix calculés sur les ventes portant sur un seul logement, valeurs aberrantes écartées "
            f"(bornes {dvf.PRIX_M2_MIN}–{dvf.PRIX_M2_MAX} €/m²). La médiane est plus représentative que la "
            "moyenne sur de petits volumes."
        )


# --------------------------------------------------------------------------- #
# Typologies
# --------------------------------------------------------------------------- #
with onglets[3]:
    if table_demande.empty:
        st.info("Pas assez de ventes pour analyser les typologies.")
    else:
        affichage = table_demande.rename(
            columns={
                "segment": "Typologie",
                "type": "Type",
                "ventes_recentes": f"Ventes ({fenetre} mois)",
                "ventes_periode_precedente": "Ventes période précédente",
                "part_marche_pct": "Part de marché (%)",
                "evolution_volume_pct": "Évolution des volumes (%)",
                "prix_m2_median": "Prix médian €/m²",
                "prix_median": "Prix médian du bien",
                "surface_mediane": "Surface médiane (m²)",
                "evolution_prix_m2_3ans_pct": "Évolution prix/m² 3 ans (%)",
                "score_demande": "Score de demande",
                "retenu": "Classée",
            }
        )
        st.dataframe(affichage.round(1), hide_index=True, width="stretch")

        classees = table_demande[table_demande["retenu"]]
        if not classees.empty:
            st.bar_chart(classees.set_index("segment")["score_demande"].rename("Score de demande"))
            st.bar_chart(classees.set_index("segment")["ventes_recentes"].rename(f"Ventes ({fenetre} mois)"))

        hors = vue_demande.get("hors_analyse") if vue_demande else None
        if hors is not None and not hors.empty:
            st.caption(
                "Typologies trop peu représentées pour être classées : "
                + ", ".join(f"{r['segment']} ({int(r['ventes_recentes'])} vente(s))" for _, r in hors.iterrows())
            )

        st.markdown(
            """
**Lecture du score** — il combine, en rangs relatifs : la part de marché (40 %), l'évolution des volumes
entre les deux dernières périodes (25 %), l'évolution du prix au m² sur 3 ans (25 %) et le volume absolu
de ventes (10 %). Une typologie qui se vend beaucoup, de plus en plus, et dont le prix progresse,
obtient un score élevé ; elle s'écoule vite mais se négocie peu. Une typologie à score faible se revend
plus difficilement : décote à l'achat plus forte, délai de sortie plus long.
            """
        )


# --------------------------------------------------------------------------- #
# Actualité locale
# --------------------------------------------------------------------------- #
with onglets[4]:
    mois_actu = st.select_slider(
        "Profondeur de la veille", options=[6, 12, 24, 36], value=24, format_func=lambda m: f"{m} mois"
    )
    try:
        actus = _actualites(nom, commune.get("codeDepartement"), mois_actu)
    except SourceError as exc:
        actus = {"themes": {}, "erreurs": [str(exc)]}

    if not actus["themes"]:
        st.info("Aucune actualité trouvée pour cette commune sur la période.")
    for theme, articles in actus["themes"].items():
        st.subheader(theme)
        for article in articles:
            date = article["date"].strftime("%d/%m/%Y") if article.get("date") else "date inconnue"
            st.markdown(f"- [{article['titre']}]({article['lien']}) — *{article.get('source') or 'source inconnue'}*, {date}")
    for erreur in actus.get("erreurs", []):
        st.caption(f"⚠️ {erreur}")

    st.divider()
    st.subheader("Établissements scolaires")
    try:
        ecoles = _ecoles(code)
        st.write(f"**{ecoles['total']}** établissements recensés dans l'annuaire de l'Éducation nationale.")
        if ecoles["repartition"]:
            st.dataframe(
                pd.DataFrame(sorted(ecoles["repartition"].items()), columns=["Type", "Nombre"]),
                hide_index=True,
            )
        if ecoles["ouvertures_recentes"]:
            st.write("**Ouvertures des 5 dernières années :**")
            st.dataframe(pd.DataFrame(ecoles["ouvertures_recentes"]), hide_index=True, width="stretch")
    except SourceError as exc:
        st.caption(f"Annuaire de l'éducation indisponible : {exc}")


# --------------------------------------------------------------------------- #
# Méthode et sources
# --------------------------------------------------------------------------- #
with onglets[5]:
    st.markdown(
        f"""
### Sources

| Donnée | Source | Fraîcheur |
|---|---|---|
| Communes, codes postaux, population de référence | API Découpage administratif (`geo.api.gouv.fr`) | continue |
| Population municipale par millésime | Insee, populations légales (recensement) | décalage de 3 ans |
| Ventes, prix, typologies | DVF géolocalisées (DGFiP / data.gouv.fr) | semestrielle, décalage de 6 à 12 mois |
| Actualité locale | Google Actualités (flux RSS) | continue |
| Établissements scolaires | Annuaire de l'Éducation nationale (`data.education.gouv.fr`) | continue |

### Traitements

1. **Sélection des ventes** : natures retenues {', '.join(dvf.NATURES_RETENUES)} ; seuls les appartements
   et maisons sont conservés.
2. **Maille d'analyse** : une mutation DVF est éclatée en plusieurs lignes (lots, parcelles, dépendances).
   Seules les ventes portant sur **un unique logement** sont retenues, ce qui exclut les ventes en bloc
   et les lots multiples, non comparables.
3. **Nettoyage** : surfaces entre {dvf.SURFACE_MIN} et {dvf.SURFACE_MAX} m², valeur foncière ≥ {dvf.VALEUR_MIN} €,
   prix au m² entre {dvf.PRIX_M2_MIN} et {dvf.PRIX_M2_MAX} €.
4. **Prix** : médiane privilégiée à la moyenne ; les deux sont affichées. Une année dont le nombre de
   ventes est inférieur à 5 n'est pas utilisée pour calculer une évolution.
5. **Demande** : score relatif par typologie (voir onglet Typologies).

### Limites à garder en tête

- DVF recense les ventes **signées**, avec un décalage de publication : la dernière année affichée est
  souvent incomplète. Les tendances récentes sont donc à confirmer par le terrain (annonces, agences).
- DVF **ne couvre pas** l'Alsace-Moselle (57, 67, 68) ni Mayotte, qui relèvent du livre foncier.
- La valeur foncière inclut parfois le mobilier ou des dépendances : le prix au m² est une approximation.
- Sur une petite commune, quelques dizaines de ventes annuelles suffisent à rendre les moyennes instables :
  privilégier les médianes et les volumes cumulés.
- Les populations légales sont publiées avec trois ans de décalage. Pour une tendance plus récente,
  croiser avec les permis de construire et les ouvertures d'équipements de l'onglet Actualité.

*Cache local : `{CACHE_DIR}` — les fichiers téléchargés y sont conservés pour accélérer les consultations suivantes.*
        """
    )